
'use server';
/**
 * @fileOverview A flow to create an expense request programmatically.
 */

import { ai } from '@/ai/genkit';
import { db } from '@/lib/firebase';
import { collection, addDoc, doc, runTransaction, getDoc, serverTimestamp, query, where, getDocs } from 'firebase/firestore';
import type { SerialNumberConfig, Department, CreateExpenseRequestInput, CreateExpenseRequestOutput } from '@/lib/types';
import { CreateExpenseRequestInputSchema, CreateExpenseRequestOutputSchema } from '@/lib/types';


const createExpenseRequestFlow = ai.defineFlow(
  {
    name: 'createExpenseRequestFlow',
    inputSchema: CreateExpenseRequestInputSchema,
    outputSchema: CreateExpenseRequestOutputSchema,
  },
  async (data) => {

    try {
      const deptRef = doc(db, 'departments', data.departmentId);
      const deptSnap = await getDoc(deptRef);
      if (!deptSnap.exists()) {
        throw new Error('Selected department not found.');
      }
      const selectedDept = deptSnap.data() as Department;

      const configRef = doc(db, 'departmentSerialConfigs', data.departmentId);
      const newRequestNo = await runTransaction(db, async (transaction) => {
        const configDoc = await transaction.get(configRef);
        if (!configDoc.exists()) {
          throw new Error(`Serial number configuration for ${selectedDept.name} not found!`);
        }
        const configData = configDoc.data() as SerialNumberConfig;
        const newIndex = configData.startingIndex;
        const formattedIndex = String(newIndex).padStart(4, '0');
        const requestNo = `${configData.prefix || ''}${configData.format || ''}${formattedIndex}${configData.suffix || ''}`;
        transaction.update(configRef, { startingIndex: newIndex + 1 });
        return requestNo;
      });

      const newExpenseRequest = {
        ...data,
        requestNo: newRequestNo,
        generatedByDepartment: selectedDept.name,
        // In a real app, you'd pass the current user's details. For this flow, we'll mark as system-generated.
        generatedByUser: 'System (Auto-generated)',
        generatedByUserId: 'system',
        receptionNo: '',
        receptionDate: '',
        createdAt: new Date().toISOString(),
      };

      await addDoc(collection(db, 'expenseRequests'), newExpenseRequest);

      // Send Email Notification via SMTP
      try {
        const { sendEmail } = await import('@/lib/mail');
        await sendEmail({
          to: 'admin@selindia.net', // Fallback or dynamic recipient
          subject: `New Expense Request: ${newRequestNo}`,
          html: `
            <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden;">
              <div style="background-color: #6366f1; padding: 24px; color: white;">
                <h1 style="margin: 0; font-size: 20px;">New Expense Request Generated</h1>
              </div>
              <div style="padding: 24px; color: #1e293b;">
                <p>A new expense request has been generated in the system.</p>
                <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
                  <tr>
                    <td style="padding: 8px 0; color: #64748b; width: 150px;">Request No:</td>
                    <td style="padding: 8px 0; font-weight: 600;">${newRequestNo}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px 0; color: #64748b;">Department:</td>
                    <td style="padding: 8px 0; font-weight: 600;">${selectedDept.name}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px 0; color: #64748b;">Generated By:</td>
                    <td style="padding: 8px 0;">System (Auto-generated)</td>
                  </tr>
                </table>
                <div style="margin-top: 32px; text-align: center;">
                  <a href="${process.env.NEXT_PUBLIC_APP_URL || 'https://selindia.net'}/dashboard/economics/balance-recon" 
                     style="background-color: #6366f1; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: 600;">
                    View in Dashboard
                  </a>
                </div>
              </div>
              <div style="background-color: #f8fafc; padding: 16px; text-align: center; font-size: 12px; color: #94a3b8;">
                &copy; ${new Date().getFullYear()} Siddhartha Engineering Limited. All rights reserved.
              </div>
            </div>
          `,
        });
      } catch (mailError) {
        console.error('Failed to send expense request email:', mailError);
      }
      
      return {
        success: true,
        message: `Expense request ${newRequestNo} has been successfully created.`,
        requestNo: newRequestNo,
      };

    } catch (error: any) {
      console.error('Error creating expense request via flow:', error);
      return {
        success: false,
        message: error.message || 'An unexpected error occurred.',
      };
    }
  }
);


export async function createExpenseRequest(input: CreateExpenseRequestInput): Promise<CreateExpenseRequestOutput> {
  return await createExpenseRequestFlow(input);
}

