
import type { Department, Project } from './types';

export const permissionModules = {
  'Module Hub': ['View Module', 'Create', 'Edit', 'Delete'],
  'Fixed Deposit Management': {
    'View Module': [],
    'Dashboard': ['View', 'Export'],
    'FD Register': ['View', 'Add', 'Edit', 'Delete', 'Export'],
    'Maturity Calendar': ['View'],
    'Available FDs': ['View', 'Assign'],
    'Assignments': ['View', 'Add', 'Approve', 'Reject', 'Release', 'Replace'],
    'Renewals': ['View', 'Request', 'Approve', 'Reject', 'Complete'],
    'Closures': ['View', 'Request', 'Approve', 'Reject', 'Complete'],
    'Releases': ['View', 'Request', 'Approve', 'Reject'],
    'Replacements': ['View', 'Request', 'Approve', 'Reject', 'Complete'],
    'Documents': ['View', 'Upload', 'Archive', 'Download'],
    'Approvals': ['View', 'Approve', 'Reject', 'Return'],
    'Reports': ['View', 'Export'],
    'Import & Reconciliation': ['View', 'Import', 'Export Exceptions'],
    'Settings': ['View', 'Edit'],
  },
  'Chat System': {
    'View Module': [],
    'Conversations': ['View', 'Send'],
    'Groups': ['Create'],
  },
  'Site Fund Requisition': [
    'View Module', 'Create Requisition', 'Edit Requisition', 'Delete Requisition',
    'Approve Request', 'Reject Request', 'View Dashboard', 'View History',
    'Revise Request', 'View Settings', 'View Summary', 'View Planned vs Actual',
    'View All'
  ],
  'Daily Requisition': {
    'View Module': [],
    'Entry Sheet': ['View', 'Add', 'Edit', 'Delete', 'View Checklist', 'Export', 'Cancel'],
    'Receiving at Finance': ['View', 'Mark as Received', 'Return to Pending', 'Reject', 'Cancel'],
    'GST & TDS Verification': ['View', 'Verify', 'Re-verify', 'Return to Pending', 'Send for Payment'],
    'Processed for Payment': ['View', 'Mark as Received for Payment', 'Approve'],
    'Manage Documents': ['View', 'Upload', 'Download', 'Mark as Missing', 'Not Required', 'Move to Pending'],
    'Settings': ['View', 'Edit Serial Nos', 'Edit User Rights', 'View Workflow', 'Edit Workflow'],
    'Reports': ['View', 'Export'],
  },
  'Site Fund Requisition 2': {
    'View Module': [],
    'Requests': ['View', 'Add', 'Edit', 'Delete', 'Approve', 'Reject', 'View All'],
    'Settings': ['View', 'Edit', 'View Workflow', 'Edit Workflow'],
    'Reports': {
      'View': [],
      'Site Fund Summary': ['View'],
    },
  },
  'Site Fund Request': {
    'View Module': [],
    'Requests': ['View', 'Add', 'Edit', 'Delete', 'Approve', 'Reject', 'View All'],
    'Settings': ['View', 'Edit', 'View Workflow', 'Edit Workflow'],
    'Reports': ['View', 'Export'],
    'Dashboard': ['View'],
  },
  'Billing Recon': {
    'View Module': [],
    'BOQ': ['View', 'Import', 'Add Manual', 'Clear BOQ', 'Delete Items'],
    'JMC': ['View', 'Create Work Order', 'Create JMC Entry', 'View Log', 'Delete JMC', 'View Certified JMC', 'View Settings', 'Edit Settings', 'Edit Serial Nos',"View Reports"],
    'MVAC': ['View', 'Create Work Order', 'Create MVAC Entry', 'View Log', 'Delete MVAC', 'View Certified MVAC', 'View Settings', 'Edit Settings', 'Edit Serial Nos',"View Reports"],
    'Billing': ['View', 'Create Bill', 'Proforma/Advance Bill', 'Edit Bill', 'Delete Bill', 'View Settings', 'Edit Settings'],
    'Combined Log': ['View'],
  },
  'Subcontractors Management': {
    'View Module': [],
    'Manage Subcontractors': ['View', 'Add', 'Edit', 'Delete'],
    'Work Order': ['View', 'Create', 'Edit', 'Delete'],
    'Billing': [
      'View',
      'Create Bill',
      'Proforma/Advance Bill',
      'View Log',
      'Edit Bill',
      'Delete Bill',
      'View Settings',
      'Edit Settings'
    ],
    'Reports': {
        'View': [],
        'Work Order Progress': ['View'],
        'Billing Summary': ['View'],
    },
  },
  'Bank Balance': {
    'View Module': [],
    'Accounts': ['View', 'Add', 'Edit', 'Delete'],
    'DP Management': ['View', 'Add', 'Delete'],
    'Opening Utilization': ['View', 'Edit'],
    'Daily Log': ['View'],
    'Interest Rate': ['View', 'Add', 'Delete'],
    'Monthly Interest': ['View', 'Edit'],
    'Expenses': ['View', 'Add', 'Delete'],
    'Receipts': ['View', 'Add', 'Delete'],
    'Internal Transaction': ['View', 'Add', 'Delete'],
    'Reports': ['View'],
  },
  'Expenses': {
    'View Module': [],
    'Departments': ['View', 'Create', 'Edit'],
    'Expense Requests': ['View All'],
    'Reports': ['View'],
    'Settings': ['View', 'Edit Serial Nos', 'Manage Accounts'],
  },
  'Loan': {
    'View Module': [],
    'Dashboard': ['View'],
    'Add Loan': ['Create'],
    'Loan Details': ['View', 'Update EMI'],
    'Reports': ['View'],
  },
  'Recurring Payments': {
    'View Module': [],
    'Dashboard': ['View', 'View Organization Totals', 'View Financial Values'],
    'Payments': ['View', 'Add', 'Edit', 'Upload Bill', 'Verify', 'Submit', 'Cancel', 'Reopen', 'Reassign', 'Send Reminder', 'Add Comment', 'Bulk Assign', 'Bulk Reminder', 'Approve', 'Record Payment'],
    'Approvals': ['View', 'Approve', 'Reject', 'Return', 'Delegate', 'Bulk Approve'],
    'Payment Processing': ['View', 'Record Payment', 'Edit Transaction', 'Delete Transaction', 'Upload Receipt', 'Close Payment'],
    'Recurring Masters': ['View', 'Add', 'Edit', 'Activate', 'Pause', 'Delete', 'Generate Manually', 'Import', 'Export'],
    'Vendors': ['View', 'Add', 'Edit'],
    'Categories': ['View', 'Add', 'Edit'],
    'Reports': ['View', 'Export', 'View Sensitive Data', 'Schedule'],
    'Settings': ['View', 'Edit', 'Manage Categories', 'Manage Approval Rules', 'Manage Notification Rules', 'Manage Automation', 'Manage Permissions', 'View Workflow', 'Edit Workflow'],
  },
  'Letter of Credit Management': {
    'View Module': [],
    'Dashboard': ['View', 'Export'],
    'LC Requests': ['View', 'Add', 'Edit', 'Delete', 'Submit', 'Cancel', 'Export'],
    'LC Register': ['View', 'Edit', 'Export'],
    'Pending Approvals': ['View', 'Approve', 'Reject', 'Return', 'Put On Hold'],
    'LC Opening': ['View', 'Add', 'Edit', 'Submit to Bank', 'Open'],
    'Hundis & Bills': ['View', 'Add', 'Edit', 'Verify', 'Accept', 'Reject'],
    'Shipment & Documents': ['View', 'Add', 'Edit', 'Upload', 'Verify', 'Resolve Discrepancy'],
    'Payment Due Calendar': ['View', 'Export'],
    'Payment Processing': ['View', 'Add', 'Edit', 'Approve', 'Record Payment', 'Reverse'],
    'LC Amendments': ['View', 'Add', 'Edit', 'Approve', 'Submit to Bank', 'Complete'],
    'Vendor Settlement': ['View', 'Add', 'Edit', 'Close'],
    'Client Recovery': ['View', 'Add', 'Edit', 'Record Receipt', 'Write Off'],
    'Margin & FD Linkage': ['View', 'Assign', 'Reserve', 'Release', 'Override'],
    'LC Closure': ['View', 'Request', 'Approve', 'Complete', 'Cancel'],
    'Reports': ['View', 'Export'],
    'Import & Reconciliation': ['View', 'Import', 'Export Exceptions', 'Activate'],
    'Settings': ['View', 'Edit'],
  },
  'Insurance': {
    'View Module': [],
    'Personal Insurance': ['View', 'Add', 'Edit', 'Delete', 'Renew', 'View History'],
    'Project Insurance': ['View', 'Add', 'Edit', 'Delete', 'Renew', 'View History', 'Mark as Not Required'],
    'Premium Due': ['View'],
    'Maturity Due': ['View'],
    'My Tasks': ['View'],
    'Reports': ['View Reports'],
    'Settings': ['View'],
    'Settings.Holders': ['View', 'Add', 'Edit', 'Delete'],
    'Settings.Companies': ['View', 'Add', 'Edit', 'Delete'],
    'Settings.Categories': ['View', 'Add', 'Edit', 'Delete'],
    'Settings.Assets': ['View', 'Add', 'Edit', 'Delete'],
  },
   'Employee': {
    'View Module': [],
    'Manage': ['View', 'Add', 'Edit', 'Delete'],
    'Sync': ['Sync from GreytHR'],
    'Categories': ['View'],
    'Position Details': ['View'],
    'Salary': ['View', 'Sync'],
  },
  'Vehicle Management': {
    'View Module': [],
    'Vehicle Master': ['View', 'Add', 'Edit', 'Delete', 'Import', 'Export'],
    'Insurance Management': ['View', 'Add', 'Edit', 'Delete', 'Import', 'Export'],
    'PUC Management': ['View', 'Add', 'Edit', 'Delete', 'Import', 'Export'],
    'Fitness Certificate Management': ['View', 'Add', 'Edit', 'Delete', 'Import', 'Export'],
    'Road Tax Management': ['View', 'Add', 'Edit', 'Delete', 'Import', 'Export'],
    'Permit Management': ['View', 'Add', 'Edit', 'Delete', 'Import', 'Export'],
    'Maintenance Management': ['View', 'Add', 'Edit', 'Delete', 'Import', 'Export'],
    'Fuel Management': ['View', 'Add', 'Edit', 'Delete', 'Import', 'Export'],
    'Trip Management': ['View', 'Add', 'Edit', 'Delete', 'Export'],
    'Driver Management': ['View', 'Add', 'Edit', 'Delete', 'Import', 'Export'],
    'Employee Trip Reimbursement': ['View', 'Add', 'Edit', 'Delete', 'Import', 'Export', 'Approve'],
    'Document Management': ['View', 'Add', 'Edit', 'Delete', 'Import', 'Export'],
    'Driver Mobile': ['View'],
    'Driver Mobile Trip': ['View', 'Add', 'Edit'],
    'Driver Mobile Fuel': ['View', 'Add', 'Edit', 'Delete'],
    'Driver Daily Status': ['View', 'Add', 'Edit', 'Delete'],
    'Settings': ['View', 'Edit'],
    'Reports': ['View', 'Export'],
  },
  'Driver Management': {
    'View Module': [],
    'Driver Mobile Hub': ['View'],
    'Assigned Vehicle Details': ['View'],
    'Driver Fuel': ['View', 'Add', 'Edit', 'Delete'],
    'Driver Daily Status': ['View', 'Add', 'Edit', 'Delete'],
    'Driver Trips': ['View', 'Add', 'Edit'],
    'Employee Trip Log': ['View', 'Add', 'Edit', 'Delete', 'Import', 'Export', 'Approve'],
    'Trip Management': ['View', 'Add', 'Edit', 'Delete', 'Export'],
  },
  'Store & Stock Management': {
    'View Module': [],
    'Projects': ['View Dashboard', 'View Inventory', 'View Transactions', 'View Conversions', 'View BOM', 'View BOQ', 'View Reports', 'View AI Forecast'],
    'Settings': ['View', 'Edit'],
  },
  'Site Account Statement': {
    'View Module': [],
    'All Projects': ['View'],
    'Dashboard': ['View'],
    'Payments': ['View', 'Add', 'Edit', 'Delete', 'Export'],
    'Expenses': ['View', 'Add', 'Edit', 'Delete', 'Export'],
    'Budget': ['View', 'Add', 'Edit', 'Delete', 'Export'],
    'Tender Budget': ['View', 'Add', 'Edit', 'Delete'],
    'Tender Forecast': ['View', 'Add', 'Edit'],
    'Expense Categories': ['View', 'Add', 'Edit', 'Delete'],
    'Project Settings': ['View', 'Add', 'Edit', 'Delete'],
    'Budget Alerts': ['View', 'Edit'],
    'Reports': ['View', 'Export'],
  },
  'Settings': {
    'View Module': [],
    'Manage Department': ['View', 'Add', 'Edit', 'Delete'],
    'Manage Project': ['View', 'Add', 'Edit', 'Delete'],
    'Employee Management': ['View', 'Add', 'Edit', 'Delete', 'Sync from GreytHR'],
    'User Management': ['View', 'Add', 'Edit', 'Delete', 'Switch User'],
    'Role Management': ['View', 'Add', 'Edit', 'Delete'],
    'Working Hrs': ['View', 'Edit'],
    'Serial No. Config': ['View', 'Edit'],
    'Appearance': ['View', 'Edit'],
    'Email Authorization': ['View', 'Send Request', 'Revoke'],
    'Login Expiry': ['View', 'Edit'],
    'Session Management': ['View', 'Delete'],
    'Location Tracking': ['View', 'Edit'],
    'Audit Logs': ['View'],
  },
};
