
import type { Department, Project } from './types';

export const permissionModules = {
  'Module Hub': ['View Module', 'Create', 'Edit', 'Delete'],
  'Site Fund Requisition': [
    'View Module', 'Create Requisition', 'Edit Requisition', 'Delete Requisition',
    'Approve Request', 'Reject Request', 'View Dashboard', 'View History',
    'Revise Request', 'View Settings', 'View Summary', 'View Planned vs Actual',
    'View All'
  ],
  'Site Fund Requisition 2': {
    'View Module': [],
    'Requests': ['View', 'New Request', 'Edit', 'Delete','View All'],
    'Reports': {
        'View': [],
        'Site Fund Summary': ['View'],
    },
    'Settings': ['View', 'Edit Workflow','View Workflow'],
  },
  'Daily Requisition': {
    'View Module': [],
    'Entry Sheet': ['View', 'Add', 'Edit', 'Delete', 'View Checklist'],
    'Receiving at Finance': ['View', 'Mark as Received', 'Return to Pending', 'Reject'],
    'GST & TDS Verification': ['View', 'Verify', 'Re-verify', 'Return to Pending'],
    'Processed for Payment': ['View', 'Mark as Received for Payment'],
    'Manage Documents': ['View', 'Upload', 'Download', 'Mark as Missing', 'Not Required', 'Move to Pending'],
    'Settings': ['View', 'Edit Serial Nos', 'Edit User Rights'],
  },
  'Billing Recon': {
    'View Module': [],
    'BOQ': ['View', 'Import', 'Add Manual', 'Clear BOQ', 'Delete Items'],
    'JMC': ['View', 'Create Work Order', 'Create JMC Entry', 'View Log', 'Delete JMC', 'View Certified JMC', 'View Settings', 'Edit Settings', 'Edit Serial Nos',"View Reports"],
    'MVAC': ['View', 'Create Work Order', 'Create MVAC Entry', 'View Log', 'Delete MVAC', 'View Certified MVAC', 'View Settings', 'Edit Settings', 'Edit Serial Nos',"View Reports"],
    'Billing': ['View', 'Create Bill', 'Proforma/Advance Bill', 'Edit Bill', 'Delete Bill', 'View Settings', 'Edit Settings'],
    'Combined Log': ['View'],
  },
  'Subcontractors Management': {
    'View Module': [],
    'Manage Subcontractors': ['View', 'Add', 'Edit', 'Delete'],
    'Work Order': ['View', 'Create', 'Edit', 'Delete'],
    'Billing': [
      'View',
      'Create Bill',
      'Proforma/Advance Bill',
      'View Log',
      'Edit Bill',
      'Delete Bill',
      'View Settings',
      'Edit Settings'
    ],
    'Reports': {
        'View': [],
        'Work Order Progress': ['View'],
        'Billing Summary': ['View'],
    },
  },
  'Bank Balance': {
    'View Module': [],
    'Accounts': ['View', 'Add', 'Edit', 'Delete'],
    'DP Management': ['View', 'Add', 'Delete'],
    'Opening Utilization': ['View', 'Edit'],
    'Daily Log': ['View'],
    'Interest Rate': ['View', 'Add', 'Delete'],
    'Monthly Interest': ['View', 'Edit'],
    'Expenses': ['View', 'Add', 'Delete'],
    'Receipts': ['View', 'Add', 'Delete'],
    'Internal Transaction': ['View', 'Add', 'Delete'],
    'Reports': ['View'],
  },
  'Expenses': {
    'View Module': [],
    'Departments': ['View', 'Create', 'Edit'],
    'Expense Requests': ['View All'],
    'Reports': ['View'],
    'Settings': ['View', 'Edit Serial Nos', 'Manage Accounts'],
  },
  'Loan': {
    'View Module': [],
    'Dashboard': ['View'],
    'Add Loan': ['Create'],
    'Loan Details': ['View', 'Update EMI'],
    'Reports': ['View'],
  },
  'Insurance': {
    'View Module': [],
    'Personal Insurance': ['View', 'Add', 'Edit', 'Delete', 'Renew', 'View History'],
    'Project Insurance': ['View', 'Add', 'Edit', 'Delete', 'Renew', 'View History', 'Mark as Not Required'],
    'Premium Due': ['View'],
    'Maturity Due': ['View'],
    'My Tasks': ['View'],
    'Reports': ['View Reports'],
    'Settings': ['View'],
    'Settings.Holders': ['View', 'Add', 'Edit', 'Delete'],
    'Settings.Companies': ['View', 'Add', 'Edit', 'Delete'],
    'Settings.Categories': ['View', 'Add', 'Edit', 'Delete'],
    'Settings.Assets': ['View', 'Add', 'Edit', 'Delete'],
  },
   'Employee': {
    'View Module': [],
    'Manage': ['View', 'Add', 'Edit', 'Delete'],
    'Sync': ['Sync from GreytHR'],
    'Categories': ['View'],
    'Position Details': ['View'],
    'Salary': ['View', 'Sync'],
  },
  'Settings': {
    'View Module': [],
    'Manage Department': ['View', 'Add', 'Edit', 'Delete'],
    'Manage Project': ['View', 'Add', 'Edit', 'Delete'],
    'Employee Management': ['View', 'Add', 'Edit', 'Delete', 'Sync from GreytHR'],
    'User Management': ['View', 'Add', 'Edit', 'Delete', 'Switch User'],
    'Role Management': ['View', 'Add', 'Edit', 'Delete'],
    'Working Hrs': ['View', 'Edit'],
    'Serial No. Config': ['View', 'Edit'],
    'Appearance': ['View', 'Edit'],
    'Email Authorization': ['View', 'Send Request', 'Revoke'],
    'Login Expiry': ['View', 'Edit'],
  },
};
