/**
 * Resolving a project from a `[project]` URL segment.
 *
 * Two incompatible slug functions grew up side by side in this codebase, hand-copied into ~40 files:
 *
 *   strict     name.toLowerCase().replace(/\s+/g,'-').replace(/[^\w-]+/g,'')
 *   canonical  ...the same, then .replace(/--+/g,'-').replace(/^-+/,'').replace(/-+$/,'')
 *
 * They agree on simple names and disagree in exactly two situations: stripping a non-word character
 * from between two words leaves two adjacent hyphens, or the name has leading/trailing whitespace.
 * (Doubled spaces are NOT a divergence — /s+/ collapses a whole run to one hyphen in both forms.)
 *
 *   "220kV Substation / Pkg-3"  ->  strict "220kv-substation--pkg-3"
 *                                   canonical "220kv-substation-pkg-3"
 *
 * The project pickers that BUILD the URLs use `canonical`; many of the pages that READ them use
 * `strict`. Any project whose name hits the disagreement therefore fails to resolve on those pages
 * with a bare "Project not found".
 *
 * Neither form can simply be made to win. `canonical` is in every generated link, while `strict` is
 * what existing `billingReconSerialConfigs` document ids were built with — see the deliberately
 * untrimmed `jmcSlugify` in jmc-module.ts and its test. So resolution is made *tolerant* instead:
 * a URL segment matches if it equals either form. That is purely additive, fixes links generated by
 * either variant, and leaves stored ids alone.
 *
 * Pure (no Firebase, no React) so the slug rules stay unit-testable.
 */

/** The non-collapsing, non-trimming form. Matches `jmcSlugify` and the stored serial-config ids. */
export function projectSlugStrict(name: unknown): string {
  return String(name ?? "")
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^\w-]+/g, "");
}

/** The collapsing, hyphen-trimming form the project pickers use to build URLs. */
export function projectSlugCanonical(name: unknown): string {
  return projectSlugStrict(name)
    .replace(/--+/g, "-")
    .replace(/^-+/, "")
    .replace(/-+$/, "");
}

/** Every form this project name could legitimately appear as in a URL. */
export function projectSlugVariants(name: unknown): string[] {
  const strict = projectSlugStrict(name);
  const canonical = projectSlugCanonical(name);
  return strict === canonical ? [strict] : [strict, canonical];
}

/** True when `slug` from the URL identifies this project under either slug form. */
export function projectMatchesSlug(name: unknown, slug: string): boolean {
  if (!slug) return false;
  return projectSlugVariants(name).includes(slug);
}

/**
 * Finds the project a `[project]` URL segment refers to, tolerating either slug form.
 *
 * Prefers an exact strict match before falling back to the canonical one, so that in the unlikely
 * event two differently-named projects collapse to the same canonical slug, the page still lands on
 * the one whose name matches the URL character for character.
 */
export function resolveProjectBySlug<T extends { projectName?: unknown }>(
  projects: T[],
  slug: string,
): T | null {
  if (!slug) return null;
  return (
    projects.find((project) => projectSlugStrict(project.projectName) === slug) ??
    projects.find((project) => projectSlugCanonical(project.projectName) === slug) ??
    null
  );
}
