import { WebSocket } from 'ws';
import fs from 'node:fs';
const W = Number(process.argv[3] ?? 1280);
const t = await fetch('http://127.0.0.1:9222/json/new?about:blank', { method: 'PUT' }).then((r) => r.json());
const ws = new WebSocket(t.webSocketDebuggerUrl);
let id = 0; const pending = new Map(); const errors = [];
ws.on('message', (raw) => { const m = JSON.parse(raw.toString()); if (m.id && pending.has(m.id)) { const p = pending.get(m.id); pending.delete(m.id); m.error ? p.reject(new Error(JSON.stringify(m.error))) : p.resolve(m.result); } else if (m.method === 'Log.entryAdded' && m.params.entry.level === 'error') errors.push(m.params.entry.text); });
await new Promise((r) => ws.on('open', r));
const send = (method, params = {}) => new Promise((resolve, reject) => { const mid = ++id; pending.set(mid, { resolve, reject }); ws.send(JSON.stringify({ id: mid, method, params })); });
const evalJs = async (e) => { const r = await send('Runtime.evaluate', { expression: e, returnByValue: true, awaitPromise: true }); if (r.exceptionDetails) throw new Error(JSON.stringify(r.exceptionDetails)); return r.result.value; };
await send('Log.enable'); await send('Page.enable');
await send('Emulation.setDeviceMetricsOverride', { width: W, height: 1000, deviceScaleFactor: 2, mobile: W < 640 });
await send('Page.navigate', { url: 'http://localhost:3000/ea-probe' });
await new Promise((r) => setTimeout(r, 6000));
console.log('headers:', await evalJs("[...document.querySelectorAll('th')].filter((h) => h.getClientRects().length).map((h) => h.innerText.trim()).join(' | ') || '(no table — phone card branch)'"));
console.log('first row:', await evalJs("(() => { const r = document.querySelector('tbody tr'); return r ? [...r.querySelectorAll('td')].map((c) => c.innerText.trim()).join(' | ') : '(none)'; })()"));
console.log('col widths:', await evalJs("(() => { const r = document.querySelector('tbody tr'); return r ? [...r.querySelectorAll('td')].map((c) => Math.round(c.getBoundingClientRect().width)).join(' | ') : '(none)'; })()"));
console.log('overflow:', await evalJs("document.documentElement.scrollWidth + ' vs viewport ' + window.innerWidth"));
console.log('console errors:', errors.length ? errors.join(' | ') : '(none)');
const h = await evalJs("Math.min(document.getElementById('probe').getBoundingClientRect().height + 20, 2200)");
await send('Emulation.setDeviceMetricsOverride', { width: W, height: Math.round(h), deviceScaleFactor: 2, mobile: W < 640 });
await new Promise((r) => setTimeout(r, 400));
const shot = await send('Page.captureScreenshot', { format: 'png' });
fs.writeFileSync(process.argv[2], Buffer.from(shot.data, 'base64'));
console.log('wrote', process.argv[2]);
ws.close(); process.exit(0);
