'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { collection, getDocs, query, where } from 'firebase/firestore';
import { AlertTriangle, Check, Eye, Link2, Loader2, Plus, RefreshCw, Search, ShieldAlert, X } from 'lucide-react';
import { db } from '@/lib/firebase';
import { useAuth } from '@/components/auth/AuthProvider';
import { useAuthorization } from '@/hooks/useAuthorization';
import { useToast } from '@/hooks/use-toast';
import type { BankAccount, Project } from '@/lib/types';
import { ACTIVE_ASSIGNMENT_STATUSES, FD_COLLECTIONS, RESERVED_ASSIGNMENT_STATUSES, assignmentOutstanding, fdStatusLabel, formatFdCurrency, toDate, type FDAssignment, type FixedDeposit } from '@/lib/fixed-deposit';
import { createFdAssignments, decideAssignment, type FDActor } from '@/lib/fixed-deposit-service';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';

type Draft = {
  instrumentType: 'BG' | 'LC'; instrumentId: string; instrumentNumber: string; bankId: string; projectId: string; partyName: string; instrumentAmount: string; marginPercentage: string; assignmentDate: string; obligationEndDate: string; expectedReleaseDate: string; purpose: string; remarks: string; reserveOnly: boolean; exceptionApproved: boolean; exceptionReason: string;
};
const today = () => new Date().toISOString().slice(0, 10);
const blank = (): Draft => ({ instrumentType: 'BG', instrumentId: '', instrumentNumber: '', bankId: '', projectId: '', partyName: '', instrumentAmount: '', marginPercentage: '100', assignmentDate: today(), obligationEndDate: '', expectedReleaseDate: '', purpose: '', remarks: '', reserveOnly: true, exceptionApproved: false, exceptionReason: '' });

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-1.5"><Label className="text-xs">{label}</Label>{children}</div>; }

export default function FDAssignmentWorkspace({ initialFdId }: { initialFdId?: string }) {
  const { user } = useAuth(); const { can, isLoading: authLoading } = useAuthorization(); const { toast } = useToast();
  const organizationId = user?.organizationId || 'default';
  const actor: FDActor | null = user ? { userId: user.id, userName: user.name, role: user.role, organizationId, organizationName: user.organizationName } : null;
  const canView = can('View', 'Fixed Deposit Management.Assignments'); const canAdd = can('Add', 'Fixed Deposit Management.Assignments'); const canApprove = can('Approve', 'Fixed Deposit Management.Assignments');
  const [fds, setFds] = useState<FixedDeposit[]>([]); const [assignments, setAssignments] = useState<FDAssignment[]>([]); const [banks, setBanks] = useState<BankAccount[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [lcs, setLcs] = useState<Record<string, any>[]>([]);
  const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [dialogOpen, setDialogOpen] = useState(Boolean(initialFdId)); const [search, setSearch] = useState(''); const [status, setStatus] = useState('ALL'); const [draft, setDraft] = useState<Draft>(blank); const [selectedAmounts, setSelectedAmounts] = useState<Record<string, string>>(initialFdId ? { [initialFdId]: '' } : {});

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const [fdSnap, assignmentSnap, bankSnap, projectSnap, lcSnap] = await Promise.all([
        getDocs(query(collection(db, FD_COLLECTIONS.deposits), where('organizationId', '==', organizationId))), getDocs(query(collection(db, FD_COLLECTIONS.assignments), where('organizationId', '==', organizationId))), getDocs(collection(db, 'bankAccounts')), getDocs(collection(db, 'projects')), getDocs(collection(db, FD_COLLECTIONS.lc)),
      ]);
      setFds(fdSnap.docs.map((entry) => ({ id: entry.id, ...entry.data() } as FixedDeposit)).filter((fd) => !fd.isDeleted)); setAssignments(assignmentSnap.docs.map((entry) => ({ id: entry.id, ...entry.data() } as FDAssignment))); setBanks(bankSnap.docs.map((entry) => ({ id: entry.id, ...entry.data() } as BankAccount)).filter((bank) => bank.status === 'Active')); setProjects(projectSnap.docs.map((entry) => ({ id: entry.id, ...entry.data() } as Project)).filter((project) => project.status === 'Active')); setLcs(lcSnap.docs.map((entry) => ({ id: entry.id, ...entry.data() })));
    } catch (error) { console.error(error); toast({ title: 'Unable to load assignments', variant: 'destructive' }); } finally { setLoading(false); }
  }, [organizationId, toast]);
  useEffect(() => { if (!authLoading && canView) void load(); else if (!authLoading) setLoading(false); }, [authLoading, canView, load]);

  const availableFds = useMemo(() => fds.filter((fd) => ['ACTIVE', 'PARTIALLY_UTILIZED', 'MATURITY_APPROACHING'].includes(fd.status) && fd.approvalStatus === 'APPROVED' && Number(fd.availableAmount) > 0), [fds]);
  const selectedBank = banks.find((bank) => bank.id === draft.bankId); const selectedProject = projects.find((project) => project.id === draft.projectId); const requiredMargin = Number(draft.instrumentAmount || 0) * Number(draft.marginPercentage || 0) / 100; const selectedTotal = Object.values(selectedAmounts).reduce((total, value) => total + Number(value || 0), 0);
  const visible = useMemo(() => assignments.filter((item) => (status === 'ALL' || item.status === status) && `${item.fdNumber} ${item.instrumentNumber} ${item.bankName} ${item.projectName || ''} ${item.partyName || ''}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => (toDate(b.createdAt)?.getTime() || 0) - (toDate(a.createdAt)?.getTime() || 0)), [assignments, search, status]);

  const selectLc = (id: string) => { const lc = lcs.find((item) => item.id === id); if (!lc) return; const bank = banks.find((item) => item.id === lc.bankId || item.bankName.toLowerCase() === String(lc.bankName || '').toLowerCase()); const project = projects.find((item) => item.id === lc.projectId || item.projectName.toLowerCase() === String(lc.projectName || '').toLowerCase()); const expiry = typeof lc.expiryDate?.toDate === 'function' ? lc.expiryDate.toDate().toISOString().slice(0, 10) : String(lc.expiryDate || ''); const due = typeof lc.actualDueDate?.toDate === 'function' ? lc.actualDueDate.toDate().toISOString().slice(0, 10) : typeof lc.expectedDueDate?.toDate === 'function' ? lc.expectedDueDate.toDate().toISOString().slice(0, 10) : String(lc.actualDueDate || lc.expectedDueDate || expiry); setDraft((current) => ({ ...current, instrumentId: id, instrumentNumber: String(lc.bankLcNumber || lc.internalReferenceNumber || ''), bankId: bank?.id || String(lc.bankId || ''), projectId: project?.id || String(lc.projectId || ''), partyName: String(lc.vendorName || ''), instrumentAmount: String(lc.openedAmount || ''), obligationEndDate: due || expiry, expectedReleaseDate: due || expiry })); };
  const toggleFd = (fdId: string) => setSelectedAmounts((current) => current[fdId] !== undefined ? Object.fromEntries(Object.entries(current).filter(([key]) => key !== fdId)) : { ...current, [fdId]: '' });

  const save = async () => {
    if (!actor) return; setWorking(true);
    try {
      await createFdAssignments({ instrumentType: draft.instrumentType, instrumentId: draft.instrumentId, instrumentNumber: draft.instrumentNumber, bankId: draft.bankId, bankName: selectedBank?.bankName || '', projectId: draft.projectId, projectName: selectedProject?.projectName || '', partyName: draft.partyName, instrumentAmount: Number(draft.instrumentAmount), marginPercentage: Number(draft.marginPercentage), requiredMarginAmount: requiredMargin, assignmentDate: draft.assignmentDate, obligationEndDate: draft.obligationEndDate, expectedReleaseDate: draft.expectedReleaseDate, purpose: draft.purpose, remarks: draft.remarks, exceptionApproved: draft.exceptionApproved, exceptionReason: draft.exceptionReason, reserveOnly: draft.reserveOnly, items: Object.entries(selectedAmounts).map(([fdId, amount]) => ({ fdId, amount: Number(amount) })) }, actor);
      toast({ title: draft.reserveOnly ? 'FD amount reserved' : 'FD assignment created', description: `${formatFdCurrency(selectedTotal)} allocated to ${draft.instrumentType} ${draft.instrumentNumber}.` }); setDialogOpen(false); setDraft(blank()); setSelectedAmounts({}); await load();
    } catch (error) { toast({ title: 'Assignment failed', description: error instanceof Error ? error.message : 'Please review the assignment.', variant: 'destructive' }); } finally { setWorking(false); }
  };
  const decide = async (id: string, action: 'APPROVE' | 'REJECT') => { if (!actor) return; setWorking(true); try { await decideAssignment(id, action, '', actor); toast({ title: `Assignment ${action.toLowerCase()}d` }); await load(); } catch (error) { toast({ title: 'Action failed', description: error instanceof Error ? error.message : '', variant: 'destructive' }); } finally { setWorking(false); } };

  if (authLoading || loading) return <div className="flex min-h-[45vh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin" /></div>;
  if (!canView) return <Card><CardHeader><CardTitle>Access Denied</CardTitle></CardHeader><CardContent className="flex justify-center py-10"><ShieldAlert className="h-12 w-12 text-destructive" /></CardContent></Card>;

  return <div className="space-y-4"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-bold">FD Assignments</h1><p className="text-sm text-muted-foreground">Reserve and assign one or more FDs against BG and LC instruments.</p></div><div className="flex gap-2">{canAdd && <Button onClick={() => setDialogOpen(true)}><Plus className="mr-2 h-4 w-4" />New Assignment</Button>}<Button variant="outline" size="icon" onClick={() => void load()}><RefreshCw className="h-4 w-4" /></Button></div></div>
    <div className="grid gap-3 sm:grid-cols-4">{[['Active', assignments.filter((a) => ACTIVE_ASSIGNMENT_STATUSES.includes(a.status)).length], ['Reserved', assignments.filter((a) => RESERVED_ASSIGNMENT_STATUSES.includes(a.status)).length], ['Released', assignments.filter((a) => a.status === 'RELEASED').length], ['Active Amount', formatFdCurrency(assignments.filter((a) => ACTIVE_ASSIGNMENT_STATUSES.includes(a.status)).reduce((sum, a) => sum + assignmentOutstanding(a), 0))]].map(([label, value]) => <Card key={String(label)}><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></CardContent></Card>)}</div>
    <Card><CardContent className="flex flex-col gap-2 p-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input className="pl-9" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search FD, instrument, bank, project…" /></div><Select value={status} onValueChange={setStatus}><SelectTrigger className="sm:w-52"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">All statuses</SelectItem>{['RESERVED', 'PENDING_APPROVAL', 'ACTIVE', 'PARTIALLY_RELEASED', 'RELEASED', 'REPLACED', 'CANCELLED', 'REJECTED'].map((value) => <SelectItem key={value} value={value}>{fdStatusLabel(value)}</SelectItem>)}</SelectContent></Select></CardContent></Card>
    <Card><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>FD</TableHead><TableHead>Instrument</TableHead><TableHead>Project / Party</TableHead><TableHead className="text-right">Assigned</TableHead><TableHead className="text-right">Active</TableHead><TableHead>Expected Release</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{visible.map((item) => <TableRow key={item.id}><TableCell><Link className="font-medium text-blue-700 hover:underline" href={`/fixed-deposit/${item.fdId}`}>{item.fdNumber}</Link><p className="text-xs text-muted-foreground">{item.bankName}</p></TableCell><TableCell><Badge variant="outline">{item.instrumentType}</Badge> {item.instrumentNumber}</TableCell><TableCell>{item.projectName || 'Unassigned'}<p className="text-xs text-muted-foreground">{item.partyName || '-'}</p></TableCell><TableCell className="text-right">{formatFdCurrency(item.assignmentAmount)}</TableCell><TableCell className="text-right">{formatFdCurrency(assignmentOutstanding(item))}</TableCell><TableCell>{toDate(item.expectedReleaseDate)?.toLocaleDateString('en-IN') || '-'}</TableCell><TableCell><Badge variant="outline">{fdStatusLabel(item.status)}</Badge></TableCell><TableCell><div className="flex justify-end gap-1"><Button asChild size="icon" variant="ghost"><Link href={`/fixed-deposit/${item.fdId}`}><Eye className="h-4 w-4" /></Link></Button>{canApprove && RESERVED_ASSIGNMENT_STATUSES.includes(item.status) && <><Button size="icon" variant="ghost" className="text-emerald-700" onClick={() => void decide(item.id, 'APPROVE')}><Check className="h-4 w-4" /></Button><Button size="icon" variant="ghost" className="text-rose-700" onClick={() => void decide(item.id, 'REJECT')}><X className="h-4 w-4" /></Button></>} {ACTIVE_ASSIGNMENT_STATUSES.includes(item.status) && <Button asChild size="sm" variant="ghost"><Link href={`/fixed-deposit/releases?assignmentId=${item.id}`}>Release</Link></Button>}<Button asChild size="sm" variant="ghost"><Link href={`/fixed-deposit/${item.fdId}/replace?assignmentId=${item.id}`}>Replace</Link></Button></div></TableCell></TableRow>)}{!visible.length && <TableRow><TableCell colSpan={8} className="h-28 text-center text-muted-foreground">No assignments found.</TableCell></TableRow>}</TableBody></Table></div></CardContent></Card>

    <Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogContent className="max-h-[94vh] max-w-5xl overflow-y-auto"><DialogHeader><DialogTitle>Assign FDs to BG or LC</DialogTitle><DialogDescription>Amounts are reserved first when approval is required. Multiple FDs may fund one instrument.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
      <Field label="Instrument Type"><Select value={draft.instrumentType} onValueChange={(value: 'BG' | 'LC') => setDraft({ ...blank(), instrumentType: value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="BG">Bank Guarantee</SelectItem><SelectItem value="LC">Letter of Credit</SelectItem></SelectContent></Select></Field>
      {draft.instrumentType === 'LC' && <Field label="Existing LC"><Select value={draft.instrumentId || 'manual'} onValueChange={(value) => value === 'manual' ? setDraft((d) => ({ ...d, instrumentId: '' })) : selectLc(value)}><SelectTrigger><SelectValue placeholder="Select LC or enter manually" /></SelectTrigger><SelectContent><SelectItem value="manual">Manual entry</SelectItem>{lcs.map((lc) => <SelectItem key={lc.id} value={lc.id}>{lc.bankLcNumber || lc.internalReferenceNumber || lc.id}</SelectItem>)}</SelectContent></Select></Field>}
      <Field label={`${draft.instrumentType} Number *`}><Input value={draft.instrumentNumber} onChange={(e) => setDraft((d) => ({ ...d, instrumentNumber: e.target.value }))} /></Field><Field label="Bank *"><Select value={draft.bankId} onValueChange={(value) => setDraft((d) => ({ ...d, bankId: value }))}><SelectTrigger><SelectValue placeholder="Select bank" /></SelectTrigger><SelectContent>{banks.map((bank) => <SelectItem key={bank.id} value={bank.id}>{bank.bankName} · {bank.branch}</SelectItem>)}</SelectContent></Select></Field><Field label="Project"><Select value={draft.projectId || 'none'} onValueChange={(value) => setDraft((d) => ({ ...d, projectId: value === 'none' ? '' : value }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Unassigned</SelectItem>{projects.map((project) => <SelectItem key={project.id} value={project.id}>{project.projectName}</SelectItem>)}</SelectContent></Select></Field><Field label={draft.instrumentType === 'BG' ? 'Beneficiary' : 'Vendor'}><Input value={draft.partyName} onChange={(e) => setDraft((d) => ({ ...d, partyName: e.target.value }))} /></Field><Field label="Instrument Amount"><Input type="number" value={draft.instrumentAmount} onChange={(e) => setDraft((d) => ({ ...d, instrumentAmount: e.target.value }))} /></Field><Field label="Required Margin %"><Input type="number" value={draft.marginPercentage} onChange={(e) => setDraft((d) => ({ ...d, marginPercentage: e.target.value }))} /></Field><Field label="Required Margin"><Input value={formatFdCurrency(requiredMargin)} readOnly /></Field><Field label="Assignment Date"><Input type="date" value={draft.assignmentDate} onChange={(e) => setDraft((d) => ({ ...d, assignmentDate: e.target.value }))} /></Field><Field label={draft.instrumentType === 'BG' ? 'Claim Expiry Date' : 'LC Obligation End Date'}><Input type="date" value={draft.obligationEndDate} onChange={(e) => setDraft((d) => ({ ...d, obligationEndDate: e.target.value }))} /></Field><Field label="Expected Release Date"><Input type="date" value={draft.expectedReleaseDate} onChange={(e) => setDraft((d) => ({ ...d, expectedReleaseDate: e.target.value }))} /></Field>
      <div className="flex items-center gap-3 rounded-lg border p-3"><Switch checked={draft.reserveOnly} onCheckedChange={(value) => setDraft((d) => ({ ...d, reserveOnly: value }))} /><div><p className="text-sm font-medium">Reserve first</p><p className="text-[11px] text-muted-foreground">Approval converts reservation to active assignment.</p></div></div><div className="flex items-center gap-3 rounded-lg border p-3"><Switch checked={draft.exceptionApproved} onCheckedChange={(value) => setDraft((d) => ({ ...d, exceptionApproved: value }))} /><div><p className="text-sm font-medium">Approved exception</p><p className="text-[11px] text-muted-foreground">Cross-bank or maturity exception.</p></div></div>{draft.exceptionApproved && <Field label="Exception reason"><Input value={draft.exceptionReason} onChange={(e) => setDraft((d) => ({ ...d, exceptionReason: e.target.value }))} /></Field>}
      <div className="sm:col-span-2 lg:col-span-3"><Field label="Remarks"><Textarea value={draft.remarks} onChange={(e) => setDraft((d) => ({ ...d, remarks: e.target.value }))} /></Field></div>
    </div><Card><CardHeader><CardTitle className="text-base">Available FD Allocation</CardTitle><CardDescription>Required {formatFdCurrency(requiredMargin)} · Selected {formatFdCurrency(selectedTotal)} · Balance {formatFdCurrency(Math.max(0, requiredMargin - selectedTotal))}</CardDescription></CardHeader><CardContent className="p-0"><div className="max-h-72 overflow-auto"><Table><TableHeader><TableRow><TableHead /><TableHead>FD</TableHead><TableHead>Bank</TableHead><TableHead>Maturity</TableHead><TableHead className="text-right">Available</TableHead><TableHead className="w-44">Assignment Amount</TableHead></TableRow></TableHeader><TableBody>{availableFds.map((fd) => { const selected = selectedAmounts[fd.id] !== undefined; const tooEarly = draft.obligationEndDate && (toDate(fd.maturityDate)?.getTime() || 0) < new Date(`${draft.obligationEndDate}T23:59:59`).getTime(); return <TableRow key={fd.id} className={tooEarly ? 'bg-rose-50/50' : ''}><TableCell><Checkbox checked={selected} onCheckedChange={() => toggleFd(fd.id)} /></TableCell><TableCell><p className="font-medium">{fd.fdNumber}</p><p className="text-xs text-muted-foreground">{fd.holderName}</p></TableCell><TableCell>{fd.bankName}{fd.bankId !== draft.bankId && draft.bankId && <Badge className="ml-1" variant="destructive">Cross-bank</Badge>}</TableCell><TableCell>{toDate(fd.maturityDate)?.toLocaleDateString('en-IN')}{tooEarly && <p className="flex items-center text-[11px] text-rose-600"><AlertTriangle className="mr-1 h-3 w-3" />Before obligation end</p>}</TableCell><TableCell className="text-right">{formatFdCurrency(fd.availableAmount)}</TableCell><TableCell><Input disabled={!selected} type="number" max={fd.availableAmount} value={selectedAmounts[fd.id] ?? ''} onChange={(e) => setSelectedAmounts((current) => ({ ...current, [fd.id]: e.target.value }))} /></TableCell></TableRow>; })}{!availableFds.length && <TableRow><TableCell colSpan={6} className="h-24 text-center text-muted-foreground">No eligible FDs available.</TableCell></TableRow>}</TableBody></Table></div></CardContent></Card><DialogFooter><Button variant="outline" onClick={() => setDialogOpen(false)}>Cancel</Button><Button onClick={() => void save()} disabled={working || !Object.keys(selectedAmounts).length}>{working && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}<Link2 className="mr-2 h-4 w-4" />{draft.reserveOnly ? 'Reserve FD Amount' : 'Create Assignment'}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
