'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { doc, getDoc, Timestamp } from 'firebase/firestore';
import { ArrowLeft, Calculator, Loader2, Save, ShieldAlert } from 'lucide-react';
import { db } from '@/lib/firebase'; import { useAuth } from '@/components/auth/AuthProvider'; import { useAuthorization } from '@/hooks/useAuthorization'; import { useToast } from '@/hooks/use-toast';
import { FD_COLLECTIONS, FD_PURPOSES, FD_TYPES, INTEREST_FREQUENCIES, INTEREST_METHODS, SOURCE_OF_FUNDS, calculateMaturity, fdStatusLabel, toDateInput, type FixedDeposit } from '@/lib/fixed-deposit'; import { updateFixedDepositDetails, type FDActor } from '@/lib/fixed-deposit-service';
import { Button } from '@/components/ui/button'; import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'; import { Input } from '@/components/ui/input'; import { Label } from '@/components/ui/label'; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'; import { Switch } from '@/components/ui/switch'; import { Textarea } from '@/components/ui/textarea';

type Draft = { holderName: string; holderType: string; jointHolderName: string; nomineeName: string; pan: string; beneficialOwner: string; fdType: string; purpose: string; sourceOfFunds: string; principalAmount: string; interestRate: string; interestCalculationMethod: string; interestPaymentFrequency: string; tenureDays: string; tenureMonths: string; valueDate: string; maturityDate: string; expectedInterest: string; maturityAmount: string; expectedTds: string; expectedNetProceeds: string; prematureClosurePenalty: string; eligibleMarginPercentage: string; lienMarked: boolean; lienHolder: string; lienDate: string; lienAmount: string; lienPurpose: string; bankConfirmationReference: string; autoRenewal: boolean; remarks: string };
const fromFd = (fd: FixedDeposit): Draft => ({ holderName: fd.holderName, holderType: fd.holderType || '', jointHolderName: fd.jointHolderName || '', nomineeName: fd.nomineeName || '', pan: fd.pan || '', beneficialOwner: fd.beneficialOwner || '', fdType: fd.fdType, purpose: fd.purpose, sourceOfFunds: fd.sourceOfFunds || '', principalAmount: String(fd.principalAmount), interestRate: String(fd.interestRate), interestCalculationMethod: fd.interestCalculationMethod, interestPaymentFrequency: fd.interestPaymentFrequency, tenureDays: String(fd.tenureDays || 0), tenureMonths: String(fd.tenureMonths || 0), valueDate: toDateInput(fd.valueDate), maturityDate: toDateInput(fd.maturityDate), expectedInterest: String(fd.expectedInterest), maturityAmount: String(fd.maturityAmount), expectedTds: String(fd.expectedTds), expectedNetProceeds: String(fd.expectedNetProceeds), prematureClosurePenalty: String(fd.prematureClosurePenalty || 0), eligibleMarginPercentage: String(fd.eligibleMarginPercentage), lienMarked: fd.lienMarked, lienHolder: fd.lienHolder || '', lienDate: toDateInput(fd.lienDate), lienAmount: String(fd.lienAmount || 0), lienPurpose: fd.lienPurpose || '', bankConfirmationReference: fd.bankConfirmationReference || '', autoRenewal: fd.autoRenewal, remarks: fd.remarks || '' });

export default function EditFixedDepositForm({ fdId }: { fdId: string }) {
  const router = useRouter(); const { user } = useAuth(); const { can, isLoading: authLoading } = useAuthorization(); const { toast } = useToast(); const organizationId = user?.organizationId || 'default'; const actor: FDActor | null = user ? { userId: user.id, userName: user.name, role: user.role, organizationId } : null;
  const canEdit = can('Edit', 'Fixed Deposit Management.FD Register'); const [fd, setFd] = useState<FixedDeposit | null>(null); const [draft, setDraft] = useState<Draft | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!user || authLoading) return; void getDoc(doc(db, FD_COLLECTIONS.deposits, fdId)).then((snapshot) => { if (snapshot.exists()) { const value = { id: snapshot.id, ...snapshot.data() } as FixedDeposit; if (value.organizationId === organizationId || user.role === 'Super Admin') { setFd(value); setDraft(fromFd(value)); } } }).finally(() => setLoading(false)); }, [authLoading, fdId, organizationId, user]);
  const update = (key: keyof Draft, value: string | boolean) => setDraft((current) => current ? { ...current, [key]: value } : current); const calc = useMemo(() => draft ? calculateMaturity({ principal: Number(draft.principalAmount), annualRate: Number(draft.interestRate), tenureDays: Number(draft.tenureDays) || undefined, tenureMonths: Number(draft.tenureMonths) || undefined, method: draft.interestCalculationMethod, frequency: draft.interestPaymentFrequency, manualMaturityAmount: Number(draft.maturityAmount), tdsPercentage: 10 }) : null, [draft]);
  const calculate = () => { if (!calc) return; setDraft((current) => current ? { ...current, expectedInterest: String(calc.expectedInterest), maturityAmount: String(calc.maturityAmount), expectedTds: String(calc.expectedTds), expectedNetProceeds: String(calc.expectedNetProceeds) } : current); };
  const save = async () => { if (!actor || !draft) return; if (!draft.holderName || !draft.valueDate || !draft.maturityDate || Number(draft.principalAmount) <= 0) return toast({ title: 'Check required fields', variant: 'destructive' }); setSaving(true); try { const numbers = ['principalAmount','interestRate','tenureDays','tenureMonths','expectedInterest','maturityAmount','expectedTds','expectedNetProceeds','prematureClosurePenalty','eligibleMarginPercentage','lienAmount'] as const; const payload: Record<string, unknown> = { ...draft, valueDate: Timestamp.fromDate(new Date(`${draft.valueDate}T12:00:00`)), maturityDate: Timestamp.fromDate(new Date(`${draft.maturityDate}T12:00:00`)), lienDate: draft.lienDate ? Timestamp.fromDate(new Date(`${draft.lienDate}T12:00:00`)) : null }; numbers.forEach((key) => { payload[key] = Number(draft[key]); }); await updateFixedDepositDetails(fdId, payload, actor); toast({ title: 'Fixed deposit updated' }); router.push(`/fixed-deposit/${fdId}`); } catch (error) { toast({ title: 'Update failed', description: error instanceof Error ? error.message : '', variant: 'destructive' }); } finally { setSaving(false); } };
  if (authLoading || loading) return <div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin" /></div>; if (!canEdit) return <Card><CardHeader><CardTitle>Access Denied</CardTitle></CardHeader><CardContent className="flex justify-center"><ShieldAlert className="h-12 w-12" /></CardContent></Card>; if (!fd || !draft) return <Card><CardHeader><CardTitle>Fixed deposit not found</CardTitle></CardHeader></Card>;
  return <div className="space-y-4"><div><Button asChild variant="ghost" size="sm" className="-ml-2"><Link href={`/fixed-deposit/${fdId}`}><ArrowLeft className="mr-2 h-4 w-4" />Back to FD</Link></Button><h1 className="text-2xl font-bold">Edit {fd.fdNumber}</h1><p className="text-sm text-muted-foreground">Material edits are restricted after activation; lifecycle changes use controlled workflows.</p></div><Card><CardHeader><CardTitle>Holder and Classification</CardTitle><CardDescription>{fd.referenceNumber} · {fd.bankName}</CardDescription></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{[['Holder Name','holderName'],['Holder Type','holderType'],['Joint Holder','jointHolderName'],['Nominee','nomineeName'],['PAN','pan'],['Beneficial Owner','beneficialOwner']].map(([label,key]) => <Field key={key} label={label}><Input value={draft[key as keyof Draft] as string} onChange={(e) => update(key as keyof Draft, e.target.value)} /></Field>)}<Field label="FD Type"><Select value={draft.fdType} onValueChange={(v) => update('fdType', v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{FD_TYPES.map(([value,label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></Field><Field label="Purpose"><Select value={draft.purpose} onValueChange={(v) => update('purpose', v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{FD_PURPOSES.map(([value,label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></Field><Field label="Source of Funds"><Select value={draft.sourceOfFunds} onValueChange={(v) => update('sourceOfFunds', v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{SOURCE_OF_FUNDS.map((v) => <SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></Field></CardContent></Card>
    <Card><CardHeader><CardTitle>Financial Terms</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Principal Amount','principalAmount'],['Interest Rate (%)','interestRate'],['Tenure Days','tenureDays'],['Tenure Months','tenureMonths'],['Value Date','valueDate'],['Maturity Date','maturityDate'],['Maturity Amount','maturityAmount'],['Expected Interest','expectedInterest'],['Expected TDS','expectedTds'],['Net Proceeds','expectedNetProceeds'],['Eligibility (%)','eligibleMarginPercentage'],['Premature Penalty','prematureClosurePenalty']].map(([label,key]) => <Field key={key} label={label}><Input type={key.toLowerCase().includes('date') ? 'date' : 'number'} value={draft[key as keyof Draft] as string} onChange={(e) => update(key as keyof Draft, e.target.value)} /></Field>)}<Field label="Interest Method"><Select value={draft.interestCalculationMethod} onValueChange={(v) => update('interestCalculationMethod', v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{INTEREST_METHODS.map((v) => <SelectItem key={v} value={v}>{fdStatusLabel(v)}</SelectItem>)}</SelectContent></Select></Field><Field label="Payment Frequency"><Select value={draft.interestPaymentFrequency} onValueChange={(v) => update('interestPaymentFrequency', v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{INTEREST_FREQUENCIES.map((v) => <SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></Field><div className="flex items-end"><Button type="button" variant="outline" onClick={calculate}><Calculator className="mr-2 h-4 w-4" />Recalculate</Button></div></CardContent></Card>
    <Card><CardHeader><CardTitle>Lien and Controls</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><div className="flex items-center gap-3 rounded-lg border p-3"><Switch checked={draft.lienMarked} onCheckedChange={(v) => update('lienMarked', v)} /><span className="text-sm font-medium">Lien Marked</span></div><div className="flex items-center gap-3 rounded-lg border p-3"><Switch checked={draft.autoRenewal} onCheckedChange={(v) => update('autoRenewal', v)} /><span className="text-sm font-medium">Auto Renewal</span></div>{[['Lien Holder','lienHolder'],['Lien Date','lienDate'],['Lien Amount','lienAmount'],['Lien Purpose','lienPurpose'],['Bank Confirmation','bankConfirmationReference']].map(([label,key]) => <Field key={key} label={label}><Input type={key === 'lienDate' ? 'date' : key === 'lienAmount' ? 'number' : 'text'} value={draft[key as keyof Draft] as string} onChange={(e) => update(key as keyof Draft, e.target.value)} /></Field>)}<Field label="Remarks"><Textarea value={draft.remarks} onChange={(e) => update('remarks', e.target.value)} /></Field></CardContent></Card><div className="flex justify-end gap-2"><Button asChild variant="outline"><Link href={`/fixed-deposit/${fdId}`}>Cancel</Link></Button><Button onClick={() => void save()} disabled={saving}>{saving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}<Save className="mr-2 h-4 w-4" />Save Changes</Button></div></div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>; }
