'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { addDoc, collection, doc, getDoc, getDocs, query, serverTimestamp, where } from 'firebase/firestore';
import { getDownloadURL, ref as storageRef, uploadBytes } from 'firebase/storage';
import { ArrowLeft, Download, FilePlus2, Loader2, Pencil, RefreshCw, Replace, ShieldAlert, Unlink } from 'lucide-react';
import { db, storage } from '@/lib/firebase';
import { useAuth } from '@/components/auth/AuthProvider';
import { useAuthorization } from '@/hooks/useAuthorization';
import { useToast } from '@/hooks/use-toast';
import { FD_COLLECTIONS, assignmentOutstanding, fdStatusLabel, formatFdCurrency, toDate, type FDAssignment, type FDApprovalRecord, type FDAuditEntry, type FDClosure, type FDDocument, type FDRenewal, type FixedDeposit } from '@/lib/fixed-deposit';
import { Button } from '@/components/ui/button'; import { Badge } from '@/components/ui/badge'; import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'; import { Input } from '@/components/ui/input'; import { Label } from '@/components/ui/label'; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'; import { Separator } from '@/components/ui/separator'; import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'; import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

const detailRows = (fd: FixedDeposit) => [
  ['Reference', fd.referenceNumber], ['FD Number', fd.fdNumber], ['Bank / Branch', `${fd.bankName}${fd.branchName ? ` / ${fd.branchName}` : ''}`], ['Holder', fd.holderName], ['Type', fdStatusLabel(fd.fdType)], ['Purpose', fdStatusLabel(fd.purpose)], ['Project', fd.projectName || '-'], ['Source of Funds', fd.sourceOfFunds || '-'], ['Value Date', toDate(fd.valueDate)?.toLocaleDateString('en-IN') || '-'], ['Maturity Date', toDate(fd.maturityDate)?.toLocaleDateString('en-IN') || '-'], ['Lien', fd.lienMarked ? `${fd.lienHolder || 'Marked'} · ${formatFdCurrency(fd.lienAmount || 0)}` : 'No'], ['Auto Renewal', fd.autoRenewal ? 'Yes' : 'No'],
];

export default function FDDetailPage({ fdId }: { fdId: string }) {
  const { user } = useAuth(); const { can, isLoading: authLoading } = useAuthorization(); const { toast } = useToast(); const organizationId = user?.organizationId || 'default';
  const canView = can('View', 'Fixed Deposit Management.FD Register'); const canEdit = can('Edit', 'Fixed Deposit Management.FD Register'); const canUpload = can('Upload', 'Fixed Deposit Management.Documents') || canEdit;
  const [fd, setFd] = useState<FixedDeposit | null>(null); const [assignments, setAssignments] = useState<FDAssignment[]>([]); const [renewals, setRenewals] = useState<FDRenewal[]>([]); const [closures, setClosures] = useState<FDClosure[]>([]); const [documents, setDocuments] = useState<FDDocument[]>([]); const [approvals, setApprovals] = useState<FDApprovalRecord[]>([]); const [audit, setAudit] = useState<FDAuditEntry[]>([]); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [file, setFile] = useState<File | null>(null); const [documentType, setDocumentType] = useState('FD_RECEIPT');
  const load = useCallback(async () => { setLoading(true); try { const fdSnap = await getDoc(doc(db, FD_COLLECTIONS.deposits, fdId)); if (!fdSnap.exists()) { setFd(null); return; } const nextFd = { id: fdSnap.id, ...fdSnap.data() } as FixedDeposit; if (nextFd.organizationId !== organizationId && user?.role !== 'Super Admin') throw new Error('Organization access denied.'); const [a, r, c, d, p, l] = await Promise.all([getDocs(query(collection(db, FD_COLLECTIONS.assignments), where('fdId', '==', fdId))), getDocs(query(collection(db, FD_COLLECTIONS.renewals), where('oldFdId', '==', fdId))), getDocs(query(collection(db, FD_COLLECTIONS.closures), where('fdId', '==', fdId))), getDocs(query(collection(db, FD_COLLECTIONS.documents), where('fdId', '==', fdId))), getDocs(query(collection(db, FD_COLLECTIONS.approvals), where('fdId', '==', fdId))), getDocs(query(collection(db, FD_COLLECTIONS.audit), where('fdId', '==', fdId)))]); setFd(nextFd); setAssignments(a.docs.map((entry) => ({ id: entry.id, ...entry.data() } as FDAssignment))); setRenewals(r.docs.map((entry) => ({ id: entry.id, ...entry.data() } as FDRenewal))); setClosures(c.docs.map((entry) => ({ id: entry.id, ...entry.data() } as FDClosure))); setDocuments(d.docs.map((entry) => ({ id: entry.id, ...entry.data() } as FDDocument))); setApprovals(p.docs.map((entry) => ({ id: entry.id, ...entry.data() } as FDApprovalRecord))); setAudit(l.docs.map((entry) => ({ id: entry.id, ...entry.data() } as FDAuditEntry))); } catch (error) { toast({ title: 'Unable to load FD record', description: error instanceof Error ? error.message : '', variant: 'destructive' }); } finally { setLoading(false); } }, [fdId, organizationId, toast, user?.role]);
  useEffect(() => { if (!authLoading && canView) void load(); else if (!authLoading) setLoading(false); }, [authLoading, canView, load]);
  const upload = async () => { if (!file || !fd || !user) return; setUploading(true); try { const safeName = file.name.replace(/[^A-Za-z0-9._-]/g, '_'); const path = `organizations/${organizationId}/fixed-deposits/${fd.id}/${documentType}/${Date.now()}-${safeName}`; const target = storageRef(storage, path); await uploadBytes(target, file); const fileUrl = await getDownloadURL(target); await addDoc(collection(db, FD_COLLECTIONS.documents), { organizationId, module: 'Fixed Deposit Management', fdId: fd.id, documentType, fileName: file.name, fileUrl, storagePath: path, version: documents.filter((item) => item.documentType === documentType).length + 1, status: 'ACTIVE', uploadedBy: user.id, uploadedByName: user.name, uploadedAt: serverTimestamp() }); await addDoc(collection(db, FD_COLLECTIONS.audit), { organizationId, module: 'Fixed Deposit Management', recordType: 'DOCUMENT', recordId: fd.id, fdId: fd.id, action: 'DOCUMENT_UPLOADED', summary: `${documentType} uploaded: ${file.name}`, userId: user.id, userName: user.name, userRole: user.role || '', page: `/fixed-deposit/${fd.id}`, createdAt: serverTimestamp() }); toast({ title: 'Document uploaded' }); setFile(null); await load(); } catch (error) { toast({ title: 'Upload failed', description: error instanceof Error ? error.message : '', variant: 'destructive' }); } finally { setUploading(false); } };
  if (authLoading || loading) return <div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin" /></div>; if (!canView) return <Card><CardHeader><CardTitle>Access Denied</CardTitle></CardHeader><CardContent className="flex justify-center"><ShieldAlert className="h-12 w-12" /></CardContent></Card>; if (!fd) return <Card><CardHeader><CardTitle>Fixed deposit not found</CardTitle><CardDescription>The record may have been removed or is outside your organization.</CardDescription></CardHeader><CardContent><Button asChild variant="outline"><Link href="/fixed-deposit/register"><ArrowLeft className="mr-2 h-4 w-4" />Back to Register</Link></Button></CardContent></Card>;
  return <div className="space-y-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><Button asChild variant="ghost" size="sm" className="-ml-2 mb-1"><Link href="/fixed-deposit/register"><ArrowLeft className="mr-1.5 h-4 w-4" />FD Register</Link></Button><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold">{fd.fdNumber}</h1><Badge>{fdStatusLabel(fd.status)}</Badge><Badge variant="outline">{fdStatusLabel(fd.approvalStatus)}</Badge></div><p className="text-sm text-muted-foreground">{fd.referenceNumber} · {fd.bankName} · {fd.holderName}</p></div><div className="flex flex-wrap justify-end gap-2">{canEdit && <Button asChild variant="outline"><Link href={`/fixed-deposit/${fd.id}/edit`}><Pencil className="mr-2 h-4 w-4" />Edit</Link></Button>}<Button asChild variant="outline"><Link href={`/fixed-deposit/${fd.id}/assign`}>Assign</Link></Button><Button asChild variant="outline"><Link href={`/fixed-deposit/${fd.id}/renew`}>Renew</Link></Button><Button asChild variant="outline"><Link href={`/fixed-deposit/${fd.id}/close`}>Close</Link></Button><Button size="icon" variant="outline" onClick={() => void load()}><RefreshCw className="h-4 w-4" /></Button></div></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[['Principal',fd.principalAmount],['Eligible Value',fd.eligibleValue],['BG Utilised',fd.bgUtilizedAmount],['LC Utilised',fd.lcUtilizedAmount],['Available',fd.availableAmount]].map(([label, value]) => <Card key={String(label)}><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-lg font-bold">{formatFdCurrency(Number(value))}</p></CardContent></Card>)}</div>
    <Tabs defaultValue="overview"><TabsList className="h-auto flex-wrap justify-start"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="financial">Financial</TabsTrigger><TabsTrigger value="assignments">Assignments ({assignments.length})</TabsTrigger><TabsTrigger value="renewal">Renewal</TabsTrigger><TabsTrigger value="closure">Closure</TabsTrigger><TabsTrigger value="documents">Documents ({documents.length})</TabsTrigger><TabsTrigger value="approval">Approval</TabsTrigger><TabsTrigger value="audit">Audit</TabsTrigger></TabsList>
      <TabsContent value="overview"><Card><CardHeader><CardTitle>Basic Information</CardTitle></CardHeader><CardContent className="grid gap-x-8 gap-y-4 sm:grid-cols-2 xl:grid-cols-3">{detailRows(fd).map(([label, value]) => <div key={label}><p className="text-xs text-muted-foreground">{label}</p><p className="font-medium">{value}</p></div>)}<div className="sm:col-span-2 xl:col-span-3"><Separator className="my-2" /><p className="text-xs text-muted-foreground">Remarks</p><p className="whitespace-pre-wrap text-sm">{fd.remarks || '-'}</p></div></CardContent></Card></TabsContent>
      <TabsContent value="financial"><Card><CardHeader><CardTitle>Deposit and Interest</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Principal',fd.principalAmount],['Rate',`${fd.interestRate}%`],['Method',fdStatusLabel(fd.interestCalculationMethod)],['Frequency',fd.interestPaymentFrequency],['Expected Interest',fd.expectedInterest],['Maturity Amount',fd.maturityAmount],['Expected TDS',fd.expectedTds],['Expected Net Proceeds',fd.expectedNetProceeds],['Interest Received',fd.interestReceived || 0],['Eligibility %',`${fd.eligibleMarginPercentage}%`],['Reserved',fd.reservedAmount],['Total Utilised',fd.totalUtilizedAmount]].map(([label, value]) => <div key={String(label)} className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="font-semibold">{typeof value === 'number' ? formatFdCurrency(value) : value}</p></div>)}</CardContent></Card></TabsContent>
      <TabsContent value="assignments"><Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>BG / LC Assignments</CardTitle><CardDescription>Active, reserved and historical links.</CardDescription></div><Button asChild size="sm"><Link href={`/fixed-deposit/${fd.id}/assign`}><FilePlus2 className="mr-2 h-4 w-4" />Assign</Link></Button></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Instrument</TableHead><TableHead>Party / Project</TableHead><TableHead className="text-right">Assigned</TableHead><TableHead className="text-right">Outstanding</TableHead><TableHead>Status</TableHead><TableHead /></TableRow></TableHeader><TableBody>{assignments.map((item) => <TableRow key={item.id}><TableCell>{item.instrumentType} {item.instrumentNumber}</TableCell><TableCell>{item.partyName || item.projectName || '-'}</TableCell><TableCell className="text-right">{formatFdCurrency(item.assignmentAmount)}</TableCell><TableCell className="text-right">{formatFdCurrency(assignmentOutstanding(item))}</TableCell><TableCell><Badge variant="outline">{fdStatusLabel(item.status)}</Badge></TableCell><TableCell><div className="flex justify-end gap-1"><Button asChild size="icon" variant="ghost"><Link href={`/fixed-deposit/releases?assignmentId=${item.id}`}><Unlink className="h-4 w-4" /></Link></Button><Button asChild size="icon" variant="ghost"><Link href={`/fixed-deposit/${fd.id}/replace?assignmentId=${item.id}`}><Replace className="h-4 w-4" /></Link></Button></div></TableCell></TableRow>)}{!assignments.length && <TableRow><TableCell colSpan={6} className="h-24 text-center text-muted-foreground">No assignment history.</TableCell></TableRow>}</TableBody></Table></CardContent></Card></TabsContent>
      <TabsContent value="renewal"><HistoryTable rows={renewals.map((item) => [toDate(item.createdAt)?.toLocaleDateString('en-IN') || '-', `${item.oldFdNumber} → ${item.newFdNumber || '-'}`, formatFdCurrency(item.renewalPrincipalAmount), fdStatusLabel(item.status)])} empty="No renewal history." action={<Button asChild size="sm"><Link href={`/fixed-deposit/${fd.id}/renew`}>Request Renewal</Link></Button>} /></TabsContent>
      <TabsContent value="closure"><HistoryTable rows={closures.map((item) => [toDate(item.requestDate)?.toLocaleDateString('en-IN') || '-', fdStatusLabel(item.closureType), formatFdCurrency(item.netProceeds), fdStatusLabel(item.status)])} empty="No closure history." action={<Button asChild size="sm"><Link href={`/fixed-deposit/${fd.id}/close`}>Request Closure</Link></Button>} /></TabsContent>
      <TabsContent value="documents"><Card><CardHeader><CardTitle>Document Vault</CardTitle><CardDescription>Versioned storage for receipt, advice, approval, lien and closure documents.</CardDescription></CardHeader><CardContent className="space-y-4">{canUpload && <div className="grid items-end gap-3 rounded-lg border bg-muted/30 p-4 sm:grid-cols-[220px_1fr_auto]"><div className="space-y-1.5"><Label>Document Type</Label><Select value={documentType} onValueChange={setDocumentType}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{['FD_RECEIPT','BANK_DEBIT_ADVICE','APPROVAL_NOTE','LIEN_CONFIRMATION','RENEWAL_ADVICE','CLOSURE_ADVICE','INTEREST_CERTIFICATE','TDS_CERTIFICATE','OTHER'].map((value) => <SelectItem key={value} value={value}>{fdStatusLabel(value)}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1.5"><Label>File</Label><Input type="file" onChange={(event) => setFile(event.target.files?.[0] || null)} /></div><Button onClick={() => void upload()} disabled={!file || uploading}>{uploading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Upload</Button></div>}<Table><TableHeader><TableRow><TableHead>Type</TableHead><TableHead>File</TableHead><TableHead>Version</TableHead><TableHead>Uploaded By</TableHead><TableHead>Date</TableHead><TableHead /></TableRow></TableHeader><TableBody>{documents.map((item) => <TableRow key={item.id}><TableCell>{fdStatusLabel(item.documentType)}</TableCell><TableCell>{item.fileName}</TableCell><TableCell>v{item.version}</TableCell><TableCell>{item.uploadedByName}</TableCell><TableCell>{toDate(item.uploadedAt)?.toLocaleString('en-IN')}</TableCell><TableCell><Button asChild size="icon" variant="ghost"><a href={item.fileUrl} target="_blank" rel="noreferrer"><Download className="h-4 w-4" /></a></Button></TableCell></TableRow>)}{!documents.length && <TableRow><TableCell colSpan={6} className="h-24 text-center text-muted-foreground">No documents uploaded.</TableCell></TableRow>}</TableBody></Table></CardContent></Card></TabsContent>
      <TabsContent value="approval"><HistoryTable rows={approvals.map((item) => [toDate(item.requestedAt)?.toLocaleString('en-IN') || '-', item.recordType, item.requiredRole, fdStatusLabel(item.status)])} empty="No approval history." /></TabsContent>
      <TabsContent value="audit"><Card><CardHeader><CardTitle>Immutable Activity Timeline</CardTitle></CardHeader><CardContent className="space-y-3">{audit.sort((a, b) => (toDate(b.createdAt)?.getTime() || 0) - (toDate(a.createdAt)?.getTime() || 0)).map((item) => <div key={item.id} className="flex gap-3 border-b pb-3 last:border-0"><div className="mt-1 h-2 w-2 rounded-full bg-cyan-600" /><div><p className="text-sm font-medium">{item.summary}</p><p className="text-xs text-muted-foreground">{item.userName} · {toDate(item.createdAt)?.toLocaleString('en-IN')} {item.reason ? `· ${item.reason}` : ''}</p></div></div>)}{!audit.length && <p className="py-8 text-center text-sm text-muted-foreground">No audit entries.</p>}</CardContent></Card></TabsContent>
    </Tabs>
  </div>;
}

function HistoryTable({ rows, empty, action }: { rows: string[][]; empty: string; action?: React.ReactNode }) { return <Card><CardHeader className="flex-row items-center justify-between"><CardTitle>Lifecycle History</CardTitle>{action}</CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Details</TableHead><TableHead>Amount / Role</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{rows.map((row, index) => <TableRow key={`${row[0]}-${index}`}>{row.map((cell, cellIndex) => <TableCell key={cellIndex}>{cellIndex === 3 ? <Badge variant="outline">{cell}</Badge> : cell}</TableCell>)}</TableRow>)}{!rows.length && <TableRow><TableCell colSpan={4} className="h-24 text-center text-muted-foreground">{empty}</TableCell></TableRow>}</TableBody></Table></CardContent></Card>; }
