'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { collection, getDocs, query, where } from 'firebase/firestore';
import { Check, Loader2, Plus, RefreshCw, ShieldAlert, X } from 'lucide-react';
import { db } from '@/lib/firebase';
import { useAuth } from '@/components/auth/AuthProvider';
import { useAuthorization } from '@/hooks/useAuthorization';
import { useToast } from '@/hooks/use-toast';
import { ACTIVE_ASSIGNMENT_STATUSES, FD_COLLECTIONS, assignmentOutstanding, fdStatusLabel, formatFdCurrency, toDate, type FDAssignment, type FDReleaseRequest } from '@/lib/fixed-deposit';
import { decideReleaseRequest, requestAssignmentRelease, type FDActor } from '@/lib/fixed-deposit-service';
import { Button } from '@/components/ui/button'; import { Badge } from '@/components/ui/badge'; import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'; import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'; import { Input } from '@/components/ui/input'; import { Label } from '@/components/ui/label'; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'; import { Switch } from '@/components/ui/switch'; import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'; import { Textarea } from '@/components/ui/textarea';

const today = () => new Date().toISOString().slice(0, 10);
export default function FDReleaseWorkspace() {
  const params = useSearchParams(); const initialAssignment = params?.get('assignmentId') || ''; const { user } = useAuth(); const { can, isLoading: authLoading } = useAuthorization(); const { toast } = useToast(); const organizationId = user?.organizationId || 'default'; const actor: FDActor | null = user ? { userId: user.id, userName: user.name, role: user.role, organizationId } : null;
  const canView = can('View', 'Fixed Deposit Management.Releases'); const canAdd = can('Request', 'Fixed Deposit Management.Releases'); const canApprove = can('Approve', 'Fixed Deposit Management.Releases');
  const [assignments, setAssignments] = useState<FDAssignment[]>([]); const [releases, setReleases] = useState<FDReleaseRequest[]>([]); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [open, setOpen] = useState(Boolean(initialAssignment));
  const [draft, setDraft] = useState({ assignmentId: initialAssignment, amount: '', effectiveDate: today(), reason: '', bankConfirmationReference: '', authorizedOverride: false });
  const load = useCallback(async () => { setLoading(true); try { const [a, r] = await Promise.all([getDocs(query(collection(db, FD_COLLECTIONS.assignments), where('organizationId', '==', organizationId))), getDocs(query(collection(db, FD_COLLECTIONS.releases), where('organizationId', '==', organizationId)))]); setAssignments(a.docs.map((entry) => ({ id: entry.id, ...entry.data() } as FDAssignment))); setReleases(r.docs.map((entry) => ({ id: entry.id, ...entry.data() } as FDReleaseRequest))); } catch { toast({ title: 'Unable to load release management', variant: 'destructive' }); } finally { setLoading(false); } }, [organizationId, toast]);
  useEffect(() => { if (!authLoading && canView) void load(); else if (!authLoading) setLoading(false); }, [authLoading, canView, load]);
  const active = useMemo(() => assignments.filter((item) => ACTIVE_ASSIGNMENT_STATUSES.includes(item.status)), [assignments]); const selected = assignments.find((item) => item.id === draft.assignmentId); const outstanding = selected ? assignmentOutstanding(selected) : 0;
  const submit = async () => { if (!actor) return; setWorking(true); try { await requestAssignmentRelease({ assignmentId: draft.assignmentId, amount: Number(draft.amount), effectiveDate: draft.effectiveDate, reason: draft.reason, bankConfirmationReference: draft.bankConfirmationReference, authorizedOverride: draft.authorizedOverride }, actor); toast({ title: 'Release submitted for approval' }); setOpen(false); setDraft({ assignmentId: '', amount: '', effectiveDate: today(), reason: '', bankConfirmationReference: '', authorizedOverride: false }); await load(); } catch (error) { toast({ title: 'Release request failed', description: error instanceof Error ? error.message : '', variant: 'destructive' }); } finally { setWorking(false); } };
  const decide = async (id: string, action: 'APPROVE' | 'REJECT') => { if (!actor) return; setWorking(true); try { await decideReleaseRequest(id, action, '', actor); toast({ title: `Release ${action.toLowerCase()}d` }); await load(); } catch (error) { toast({ title: 'Release action failed', description: error instanceof Error ? error.message : '', variant: 'destructive' }); } finally { setWorking(false); } };
  if (authLoading || loading) return <div className="flex min-h-[45vh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin" /></div>; if (!canView) return <Card><CardHeader><CardTitle>Access Denied</CardTitle></CardHeader><CardContent className="flex justify-center"><ShieldAlert className="h-12 w-12" /></CardContent></Card>;
  return <div className="space-y-4"><div className="flex items-end justify-between"><div><h1 className="text-2xl font-bold">Release Management</h1><p className="text-sm text-muted-foreground">Partial and full release with bank confirmation and approval control.</p></div><div className="flex gap-2">{canAdd && <Button onClick={() => setOpen(true)}><Plus className="mr-2 h-4 w-4" />Request Release</Button>}<Button variant="outline" size="icon" onClick={() => void load()}><RefreshCw className="h-4 w-4" /></Button></div></div><Card><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>FD / Instrument</TableHead><TableHead>Release Type</TableHead><TableHead className="text-right">Amount</TableHead><TableHead>Effective Date</TableHead><TableHead>Confirmation</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{releases.sort((a, b) => (toDate(b.createdAt)?.getTime() || 0) - (toDate(a.createdAt)?.getTime() || 0)).map((release) => <TableRow key={release.id}><TableCell><p className="font-medium">{release.fdNumber}</p><p className="text-xs text-muted-foreground">{release.instrumentType} {release.instrumentNumber}</p></TableCell><TableCell>{release.releaseType}</TableCell><TableCell className="text-right">{formatFdCurrency(release.releaseAmount)}</TableCell><TableCell>{toDate(release.effectiveReleaseDate)?.toLocaleDateString('en-IN')}</TableCell><TableCell>{release.bankConfirmationReference || (release.authorizedOverride ? 'Authorised override' : '-')}</TableCell><TableCell><Badge variant="outline">{fdStatusLabel(release.status)}</Badge></TableCell><TableCell><div className="flex justify-end gap-1">{canApprove && release.status === 'PENDING_APPROVAL' && <><Button variant="ghost" size="icon" className="text-emerald-700" onClick={() => void decide(release.id, 'APPROVE')}><Check className="h-4 w-4" /></Button><Button variant="ghost" size="icon" className="text-rose-700" onClick={() => void decide(release.id, 'REJECT')}><X className="h-4 w-4" /></Button></>}</div></TableCell></TableRow>)}{!releases.length && <TableRow><TableCell colSpan={7} className="h-28 text-center text-muted-foreground">No release requests found.</TableCell></TableRow>}</TableBody></Table></CardContent></Card>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Request Assignment Release</DialogTitle><DialogDescription>An amount is released only after approval. Bank confirmation or an authorised override is mandatory.</DialogDescription></DialogHeader><div className="space-y-4"><div className="space-y-1.5"><Label>Active Assignment</Label><Select value={draft.assignmentId} onValueChange={(value) => setDraft((d) => ({ ...d, assignmentId: value, amount: String(assignmentOutstanding(active.find((a) => a.id === value)!)) }))}><SelectTrigger><SelectValue placeholder="Select assignment" /></SelectTrigger><SelectContent>{active.map((a) => <SelectItem key={a.id} value={a.id}>{a.fdNumber} · {a.instrumentType} {a.instrumentNumber} · {formatFdCurrency(assignmentOutstanding(a))}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-1.5"><Label>Release Amount</Label><Input type="number" max={outstanding} value={draft.amount} onChange={(e) => setDraft((d) => ({ ...d, amount: e.target.value }))} /><p className="text-xs text-muted-foreground">Outstanding: {formatFdCurrency(outstanding)}</p></div><div className="space-y-1.5"><Label>Effective Release Date</Label><Input type="date" value={draft.effectiveDate} onChange={(e) => setDraft((d) => ({ ...d, effectiveDate: e.target.value }))} /></div></div><div className="space-y-1.5"><Label>Bank Release Confirmation</Label><Input value={draft.bankConfirmationReference} onChange={(e) => setDraft((d) => ({ ...d, bankConfirmationReference: e.target.value }))} /></div><div className="flex items-center gap-3 rounded-lg border p-3"><Switch checked={draft.authorizedOverride} onCheckedChange={(value) => setDraft((d) => ({ ...d, authorizedOverride: value }))} /><div><p className="text-sm font-medium">Authorised override</p><p className="text-xs text-muted-foreground">Requires Director Finance approval.</p></div></div><div className="space-y-1.5"><Label>Release Reason</Label><Textarea value={draft.reason} onChange={(e) => setDraft((d) => ({ ...d, reason: e.target.value }))} /></div></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => void submit()} disabled={working || !draft.assignmentId}>{working && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Submit Release</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
