'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { collection, getDocs, query, where } from 'firebase/firestore';
import { Check, ExternalLink, Loader2, Plus, RefreshCw, ShieldAlert } from 'lucide-react';
import { db } from '@/lib/firebase';
import { useAuth } from '@/components/auth/AuthProvider';
import { useAuthorization } from '@/hooks/useAuthorization';
import { useToast } from '@/hooks/use-toast';
import { FD_COLLECTIONS, calculateMaturity, fdStatusLabel, formatFdCurrency, toDate, type FixedDeposit, type FDRenewal } from '@/lib/fixed-deposit';
import { approveFdRenewal, completeFdRenewal, requestFdRenewal, type FDActor } from '@/lib/fixed-deposit-service';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Textarea } from '@/components/ui/textarea';

const terminal = ['CLOSED', 'PREMATURELY_CLOSED', 'RENEWED', 'CANCELLED', 'REPLACED'];
const emptyDraft = (fdId = '') => ({ fdId, interestReceived: '', tdsAmount: '', renewalPrincipalAmount: '', additionalDepositAmount: '0', withdrawalAmount: '0', newFdNumber: '', newInterestRate: '', newMaturityDate: '', newMaturityAmount: '', renewalReason: '', assignmentsTransferred: true });

export default function FDRenewalWorkspace({ initialFdId = '' }: { initialFdId?: string }) {
  const { user } = useAuth(); const { can, isLoading: authLoading } = useAuthorization(); const { toast } = useToast();
  const organizationId = user?.organizationId || 'default';
  const actor: FDActor | null = user ? { userId: user.id, userName: user.name, role: user.role, organizationId } : null;
  const canView = can('View', 'Fixed Deposit Management.Renewals'); const canRequest = can('Request', 'Fixed Deposit Management.Renewals'); const canApprove = can('Approve', 'Fixed Deposit Management.Renewals'); const canComplete = can('Complete', 'Fixed Deposit Management.Renewals');
  const [fds, setFds] = useState<FixedDeposit[]>([]); const [renewals, setRenewals] = useState<FDRenewal[]>([]); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [open, setOpen] = useState(Boolean(initialFdId)); const [draft, setDraft] = useState(emptyDraft(initialFdId));
  const load = useCallback(async () => { setLoading(true); try { const [f, r] = await Promise.all([getDocs(query(collection(db, FD_COLLECTIONS.deposits), where('organizationId', '==', organizationId))), getDocs(query(collection(db, FD_COLLECTIONS.renewals), where('organizationId', '==', organizationId)))]); setFds(f.docs.map((entry) => ({ id: entry.id, ...entry.data() } as FixedDeposit)).filter((fd) => !fd.isDeleted)); setRenewals(r.docs.map((entry) => ({ id: entry.id, ...entry.data() } as FDRenewal))); } catch { toast({ title: 'Unable to load renewals', variant: 'destructive' }); } finally { setLoading(false); } }, [organizationId, toast]);
  useEffect(() => { if (!authLoading && canView) void load(); else if (!authLoading) setLoading(false); }, [authLoading, canView, load]);
  const eligible = useMemo(() => fds.filter((fd) => !terminal.includes(fd.status)), [fds]); const selected = fds.find((fd) => fd.id === draft.fdId);
  const selectFd = (fdId: string) => { const fd = fds.find((item) => item.id === fdId); setDraft({ ...emptyDraft(fdId), interestReceived: String(fd?.interestReceived || 0), renewalPrincipalAmount: String(fd?.maturityAmount || fd?.principalAmount || ''), newInterestRate: String(fd?.interestRate || ''), newFdNumber: fd ? `${fd.fdNumber}-R` : '' }); };
  const calculate = () => { const result = calculateMaturity({ principal: Number(draft.renewalPrincipalAmount), annualRate: Number(draft.newInterestRate), tenureDays: draft.newMaturityDate ? Math.max(1, Math.ceil((new Date(draft.newMaturityDate).getTime() - Date.now()) / 86400000)) : 365, method: selected?.interestCalculationMethod || 'COMPOUND', frequency: selected?.interestPaymentFrequency || 'On maturity' }); setDraft((value) => ({ ...value, newMaturityAmount: String(result.maturityAmount) })); };
  const submit = async () => { if (!actor) return; setWorking(true); try { await requestFdRenewal({ ...draft, interestReceived: Number(draft.interestReceived), tdsAmount: Number(draft.tdsAmount), renewalPrincipalAmount: Number(draft.renewalPrincipalAmount), additionalDepositAmount: Number(draft.additionalDepositAmount), withdrawalAmount: Number(draft.withdrawalAmount), newInterestRate: Number(draft.newInterestRate), newMaturityAmount: Number(draft.newMaturityAmount) }, actor); toast({ title: 'Renewal submitted for approval' }); setOpen(false); setDraft(emptyDraft()); await load(); } catch (error) { toast({ title: 'Renewal request failed', description: error instanceof Error ? error.message : '', variant: 'destructive' }); } finally { setWorking(false); } };
  const approve = async (renewal: FDRenewal) => { if (!actor) return; const reference = window.prompt('Bank submission/reference (optional at approval)') || ''; setWorking(true); try { await approveFdRenewal(renewal.id, reference, actor); toast({ title: 'Renewal approved and submitted to bank' }); await load(); } catch (error) { toast({ title: 'Approval failed', description: error instanceof Error ? error.message : '', variant: 'destructive' }); } finally { setWorking(false); } };
  const complete = async (renewal: FDRenewal) => { if (!actor) return; const reference = window.prompt('Enter mandatory bank renewal confirmation reference'); if (!reference) return; setWorking(true); try { const newId = await completeFdRenewal(renewal.id, reference, actor); toast({ title: 'Renewal completed', description: `New FD ${newId} created and linked assignments transferred.` }); await load(); } catch (error) { toast({ title: 'Completion failed', description: error instanceof Error ? error.message : '', variant: 'destructive' }); } finally { setWorking(false); } };
  if (authLoading || loading) return <div className="flex min-h-[45vh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin" /></div>;
  if (!canView) return <Card><CardHeader><CardTitle>Access Denied</CardTitle></CardHeader><CardContent className="flex justify-center"><ShieldAlert className="h-12 w-12" /></CardContent></Card>;
  return <div className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold">FD Renewals</h1><p className="text-sm text-muted-foreground">Approval, bank confirmation, new FD generation and assignment continuity.</p></div><div className="flex gap-2">{canRequest && <Button onClick={() => setOpen(true)}><Plus className="mr-2 h-4 w-4" />Request Renewal</Button>}<Button variant="outline" size="icon" onClick={() => void load()}><RefreshCw className="h-4 w-4" /></Button></div></div><Card><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Old / New FD</TableHead><TableHead className="text-right">Renewal Principal</TableHead><TableHead>New Maturity</TableHead><TableHead>Assignments</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{renewals.sort((a, b) => (toDate(b.createdAt)?.getTime() || 0) - (toDate(a.createdAt)?.getTime() || 0)).map((item) => <TableRow key={item.id}><TableCell><Link className="font-medium text-blue-700 hover:underline" href={`/fixed-deposit/${item.oldFdId}`}>{item.oldFdNumber}</Link><p className="text-xs text-muted-foreground">to {item.newFdNumber || 'Pending'}</p></TableCell><TableCell className="text-right">{formatFdCurrency(item.renewalPrincipalAmount)}</TableCell><TableCell>{toDate(item.newMaturityDate)?.toLocaleDateString('en-IN')}</TableCell><TableCell>{item.assignmentsTransferred ? 'Transfer' : 'Do not transfer'}</TableCell><TableCell><Badge variant="outline">{fdStatusLabel(item.status)}</Badge></TableCell><TableCell><div className="flex justify-end gap-1">{canApprove && item.status === 'PENDING_APPROVAL' && <Button size="sm" variant="outline" onClick={() => void approve(item)} disabled={working}><Check className="mr-1 h-3.5 w-3.5" />Approve</Button>}{canComplete && item.status === 'SUBMITTED_TO_BANK' && <Button size="sm" onClick={() => void complete(item)} disabled={working}>Complete</Button>}{item.newFdId && <Button asChild size="icon" variant="ghost"><Link href={`/fixed-deposit/${item.newFdId}`}><ExternalLink className="h-4 w-4" /></Link></Button>}</div></TableCell></TableRow>)}{!renewals.length && <TableRow><TableCell colSpan={6} className="h-28 text-center text-muted-foreground">No renewal requests found.</TableCell></TableRow>}</TableBody></Table></CardContent></Card>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Request FD Renewal</DialogTitle><DialogDescription>The new FD is created only after approval and bank confirmation.</DialogDescription></DialogHeader><div className="grid max-h-[65vh] gap-4 overflow-y-auto pr-1 sm:grid-cols-2"><div className="space-y-1.5 sm:col-span-2"><Label>Fixed Deposit</Label><Select value={draft.fdId} onValueChange={selectFd}><SelectTrigger><SelectValue placeholder="Select FD" /></SelectTrigger><SelectContent>{eligible.map((fd) => <SelectItem key={fd.id} value={fd.id}>{fd.fdNumber} · {fd.bankName} · {formatFdCurrency(fd.principalAmount)}</SelectItem>)}</SelectContent></Select></div>{[['New FD Number','newFdNumber'],['Renewal Principal','renewalPrincipalAmount'],['Interest Received','interestReceived'],['TDS Amount','tdsAmount'],['Additional Deposit','additionalDepositAmount'],['Withdrawal Amount','withdrawalAmount'],['New Interest Rate (%)','newInterestRate'],['New Maturity Amount','newMaturityAmount']].map(([label, key]) => <div key={key} className="space-y-1.5"><Label>{label}</Label><Input type={key === 'newFdNumber' ? 'text' : 'number'} value={draft[key as keyof typeof draft] as string} onChange={(event) => setDraft((value) => ({ ...value, [key]: event.target.value }))} /></div>)}<div className="space-y-1.5"><Label>New Maturity Date</Label><Input type="date" value={draft.newMaturityDate} onChange={(event) => setDraft((value) => ({ ...value, newMaturityDate: event.target.value }))} /></div><div className="flex items-end"><Button type="button" variant="outline" onClick={calculate}>Calculate Maturity</Button></div><div className="flex items-center gap-3 rounded-lg border p-3 sm:col-span-2"><Switch checked={draft.assignmentsTransferred} onCheckedChange={(checked) => setDraft((value) => ({ ...value, assignmentsTransferred: checked }))} /><div><p className="text-sm font-medium">Transfer active and reserved assignments</p><p className="text-xs text-muted-foreground">Preserves BG/LC linkage on the renewed FD.</p></div></div><div className="space-y-1.5 sm:col-span-2"><Label>Renewal Reason / Remarks</Label><Textarea value={draft.renewalReason} onChange={(event) => setDraft((value) => ({ ...value, renewalReason: event.target.value }))} /></div></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => void submit()} disabled={working || !draft.fdId}>{working && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Submit Renewal</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
