'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { collection, doc, getDoc, getDocs, query, where } from 'firebase/firestore';
import { ArrowLeft, CalendarClock, FileArchive, FileText, Landmark, Link2, Loader2, PencilRuler, ReceiptIndianRupee, ShieldAlert, Ship, WalletCards } from 'lucide-react';
import { db } from '@/lib/firebase';
import { useAuth } from '@/components/auth/AuthProvider';
import { useAuthorization } from '@/hooks/useAuthorization';
import { useToast } from '@/hooks/use-toast';
import { LC_COLLECTIONS, LC_PERMISSION_MODULE, formatLcCurrency, lcLabel, lcStatusTone, toLcDateInput, type LCHundi, type LCPayment, type LCRequest, type LetterOfCredit } from '@/lib/letter-of-credit';
import { FD_COLLECTIONS, type FDAssignment } from '@/lib/fixed-deposit';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';

type Row = Record<string, any> & { id: string };
const relatedCollections = ['shipments', 'documents', 'hundis', 'discrepancies', 'payments', 'amendments', 'vendorSettlements', 'recoveries', 'closures'] as const;

export default function LCDetailPage({ lcId }: { lcId: string }) {
  const { user } = useAuth(); const { can, isLoading: authLoading } = useAuthorization(); const { toast } = useToast();
  const [credit, setCredit] = useState<LetterOfCredit | null>(null); const [request, setRequest] = useState<LCRequest | null>(null); const [related, setRelated] = useState<Record<string, Row[]>>({}); const [assignments, setAssignments] = useState<FDAssignment[]>([]); const [approvals, setApprovals] = useState<Row[]>([]); const [audit, setAudit] = useState<Row[]>([]); const [loading, setLoading] = useState(true);
  const canView = can('View', `${LC_PERMISSION_MODULE}.LC Register`) || can('View', `${LC_PERMISSION_MODULE}.LC Requests`);
  const load = useCallback(async () => { setLoading(true); try { const [lcSnapshot, requestSnapshot] = await Promise.all([getDoc(doc(db, LC_COLLECTIONS.credits, lcId)), getDoc(doc(db, LC_COLLECTIONS.requests, lcId))]); let nextCredit = lcSnapshot.exists() ? ({ id: lcSnapshot.id, ...lcSnapshot.data() } as LetterOfCredit) : null; let nextRequest = requestSnapshot.exists() ? ({ id: requestSnapshot.id, ...requestSnapshot.data() } as LCRequest) : null; if (nextCredit && !nextRequest && nextCredit.requestId) { const linked = await getDoc(doc(db, LC_COLLECTIONS.requests, nextCredit.requestId)); if (linked.exists()) nextRequest = { id: linked.id, ...linked.data() } as LCRequest; } if (!nextCredit && nextRequest?.id) { const linked = await getDocs(query(collection(db, LC_COLLECTIONS.credits), where('requestId', '==', nextRequest.id))); if (!linked.empty) nextCredit = { id: linked.docs[0].id, ...linked.docs[0].data() } as LetterOfCredit; }
      const recordOrg = nextCredit?.organizationId || nextRequest?.organizationId; if (recordOrg && recordOrg !== (user?.organizationId || 'default') && user?.role !== 'Super Admin') throw new Error('Organization access denied.');
      setCredit(nextCredit); setRequest(nextRequest); const relationId = nextCredit?.id || '';
      if (relationId) { const snapshots = await Promise.all(relatedCollections.map((key) => getDocs(query(collection(db, LC_COLLECTIONS[key]), where('lcId', '==', relationId))))); const map: Record<string, Row[]> = {}; relatedCollections.forEach((key, index) => { map[key] = snapshots[index].docs.map((item) => ({ id: item.id, ...item.data() })); }); setRelated(map); const [assignmentSnapshot, approvalSnapshot, auditSnapshot] = await Promise.all([getDocs(query(collection(db, FD_COLLECTIONS.assignments), where('instrumentId', '==', relationId))), getDocs(query(collection(db, LC_COLLECTIONS.approvals), where('lcId', '==', relationId))), getDocs(query(collection(db, LC_COLLECTIONS.audit), where('lcId', '==', relationId)))]); setAssignments(assignmentSnapshot.docs.map((item) => ({ id: item.id, ...item.data() } as FDAssignment))); setApprovals(approvalSnapshot.docs.map((item) => ({ id: item.id, ...item.data() }))); setAudit(auditSnapshot.docs.map((item) => ({ id: item.id, ...item.data() }))); }
      else if (nextRequest) { const [approvalSnapshot, auditSnapshot, assignmentSnapshot] = await Promise.all([getDocs(query(collection(db, LC_COLLECTIONS.approvals), where('requestId', '==', nextRequest.id))), getDocs(query(collection(db, LC_COLLECTIONS.audit), where('requestId', '==', nextRequest.id))), getDocs(query(collection(db, FD_COLLECTIONS.assignments), where('instrumentId', '==', nextRequest.id)))]); setApprovals(approvalSnapshot.docs.map((item) => ({ id: item.id, ...item.data() }))); setAudit(auditSnapshot.docs.map((item) => ({ id: item.id, ...item.data() }))); setAssignments(assignmentSnapshot.docs.map((item) => ({ id: item.id, ...item.data() } as FDAssignment))); }
    } catch (error) { toast({ title: 'Unable to load LC detail', description: error instanceof Error ? error.message : '', variant: 'destructive' }); } finally { setLoading(false); } }, [lcId, toast, user?.organizationId, user?.role]);
  useEffect(() => { if (!authLoading && canView) void load(); else if (!authLoading) setLoading(false); }, [authLoading, canView, load]);
  if (authLoading || loading) return <div className="flex min-h-[45vh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-cyan-600" /></div>;
  if (!canView) return <Card><CardHeader><CardTitle>Access Denied</CardTitle><CardDescription>You do not have permission to view this LC.</CardDescription></CardHeader><CardContent className="flex justify-center py-8"><ShieldAlert className="h-14 w-14 text-destructive" /></CardContent></Card>;
  if (!credit && !request) return <Card><CardHeader><CardTitle>LC not found</CardTitle><CardDescription>The requested LC or request record does not exist.</CardDescription></CardHeader><CardContent><Button asChild variant="outline"><Link href="/letter-of-credit/register"><ArrowLeft className="mr-2 h-4 w-4" />Back to Register</Link></Button></CardContent></Card>;
  const status = credit?.status || request?.status || ''; const title = credit?.bankLcNumber || request?.referenceNumber || ''; const currency = credit?.currency || request?.currency || 'INR';
  return <div className="space-y-4"><Card className="overflow-hidden border-0 bg-gradient-to-r from-slate-950 via-cyan-950 to-blue-950 text-white"><CardContent className="flex flex-col gap-4 p-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-start gap-3"><Button asChild variant="secondary" size="icon"><Link href="/letter-of-credit/register"><ArrowLeft className="h-4 w-4" /></Link></Button><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold">{title}</h1><Badge className="bg-white/15 text-white">{lcLabel(status)}</Badge></div><p className="mt-1 text-sm text-cyan-100">{credit?.internalReferenceNumber || 'LC Request'} · {credit?.vendorName || request?.vendorName} · {credit?.projectName || request?.projectName}</p></div></div><div className="flex flex-wrap gap-2">{request?.status === 'APPROVED' && !credit && <Button asChild variant="secondary"><Link href={`/letter-of-credit/opening?requestId=${request.id}`}><Landmark className="mr-2 h-4 w-4" />Open LC</Link></Button>}{credit && <><Button asChild variant="secondary"><Link href={`/letter-of-credit/hundis?lcId=${credit.id}`}><ReceiptIndianRupee className="mr-2 h-4 w-4" />Record Hundi</Link></Button><Button asChild variant="secondary"><Link href={`/letter-of-credit/payments?lcId=${credit.id}`}><WalletCards className="mr-2 h-4 w-4" />Payment</Link></Button><Button asChild variant="secondary"><Link href={`/letter-of-credit/closures?lcId=${credit.id}`}><FileArchive className="mr-2 h-4 w-4" />Close</Link></Button></>}</div></CardContent></Card>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label={credit ? 'Opened Amount' : 'Requested Amount'} value={formatLcCurrency(credit?.openedAmount || request?.requestedAmount || 0, currency)} /><Metric label="Accepted Drawings" value={formatLcCurrency(credit?.totalAcceptedAmount || 0, currency)} /><Metric label="Paid Amount" value={formatLcCurrency(credit?.totalPaidAmount || 0, currency)} /><Metric label="Payment Outstanding" value={formatLcCurrency(credit?.outstandingAmount || 0, currency)} alert /></div>
    <Tabs defaultValue="overview"><TabsList className="flex h-auto flex-wrap justify-start"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="terms">Terms</TabsTrigger><TabsTrigger value="margin">Margin</TabsTrigger><TabsTrigger value="hundis">Hundis</TabsTrigger><TabsTrigger value="payments">Payments</TabsTrigger><TabsTrigger value="amendments">Amendments</TabsTrigger><TabsTrigger value="settlement">Settlement</TabsTrigger><TabsTrigger value="recovery">Recovery</TabsTrigger><TabsTrigger value="documents">Documents</TabsTrigger><TabsTrigger value="approvals">Approvals</TabsTrigger><TabsTrigger value="audit">Audit</TabsTrigger></TabsList>
      <TabsContent value="overview"><InfoCard title="LC Overview" items={credit ? [['Bank LC Number', credit.bankLcNumber], ['Internal Reference', credit.internalReferenceNumber], ['Bank', credit.bankName], ['Vendor', credit.vendorName], ['Project', credit.projectName], ['Purchase Order', credit.purchaseOrderNumber], ['Opening Date', toLcDateInput(credit.openingDate)], ['Expiry Date', toLcDateInput(credit.expiryDate)], ['Expected Due Date', toLcDateInput(credit.expectedDueDate)], ['Actual Due Date', toLcDateInput(credit.actualDueDate)], ['Unutilised Amount', formatLcCurrency(credit.unutilizedAmount, currency)], ['Status', lcLabel(credit.status)]] : [['Reference', request?.referenceNumber], ['Organization', request?.organizationName], ['Vendor', request?.vendorName], ['Project', request?.projectName], ['Purchase Order', request?.purchaseOrderNumber], ['Preferred Bank', request?.preferredBankName], ['Required Opening', toLcDateInput(request?.requiredOpeningDate)], ['Proposed Expiry', toLcDateInput(request?.proposedExpiryDate)], ['Workflow Stage', lcLabel(request?.workflowStage)], ['Status', lcLabel(request?.status)]]} /></TabsContent>
      <TabsContent value="terms"><InfoCard title="Terms & Conditions" items={[['LC Type', lcLabel(credit?.lcType || request?.lcType)], ['Sight / Usance', request?.sightOrUsance], ['Usance Period', `${credit?.usancePeriodDays || request?.usancePeriodDays || 0} days`], ['Due-date Basis', lcLabel(credit?.dueDateBasis || request?.dueDateBasis)], ['Partial Shipment', request?.partialShipmentAllowed ? 'Allowed' : 'Not allowed'], ['Partial Drawing', request?.partialDrawingAllowed ? 'Allowed' : 'Not allowed'], ['Tolerance', `${request?.tolerancePercentage || 0}%`], ['Presentation Period', `${credit?.presentationPeriodDays || request?.presentationPeriodDays || 0} days`], ['Incoterm', request?.incoterm], ['Special Conditions', request?.specialConditions]]} /></TabsContent>
      <TabsContent value="margin"><div className="space-y-4"><InfoCard title="Margin & Collateral" items={[['Required Margin', formatLcCurrency(credit?.requiredMarginAmount || request?.requiredMarginAmount || 0, currency)], ['FD Margin', formatLcCurrency(credit?.fdMarginAmount || request?.fdMarginAmount || 0, currency)], ['Cash Margin', formatLcCurrency(credit?.cashMarginAmount || request?.cashMarginAmount || 0, currency)], ['Other Collateral', formatLcCurrency(credit?.otherCollateralAmount || request?.otherCollateralAmount || 0, currency)], ['Margin %', `${credit?.marginPercentage || request?.marginPercentage || 0}%`], ['Assignments', String(assignments.length)]]} /><SimpleTable title="FD Assignments" rows={assignments} columns={[['fdNumber', 'FD Number'], ['bankName', 'Bank'], ['assignmentAmount', 'Assigned', money], ['activeAmount', 'Active', money], ['expectedReleaseDate', 'Expected Release', dateValue], ['status', 'Status', labelValue]]} /></div></TabsContent>
      <TabsContent value="hundis"><SimpleTable title="Hundis & Bills" rows={related.hundis || []} columns={[['hundiNumber', 'Hundi'], ['invoiceNumber', 'Invoice'], ['claimedAmount', 'Claimed', money], ['acceptedAmount', 'Accepted', money], ['rejectedAmount', 'Rejected', money], ['calculatedDueDate', 'Due Date', dateValue], ['status', 'Status', labelValue]]} /></TabsContent>
      <TabsContent value="payments"><SimpleTable title="Payments" rows={related.payments || []} columns={[['paymentDate', 'Date', dateValue], ['hundiNumber', 'Hundi'], ['paidAmount', 'Paid', money], ['bankCommission', 'Commission', money], ['netDebitAmount', 'Net Debit', money], ['utrNumber', 'UTR'], ['status', 'Status', labelValue]]} /></TabsContent>
      <TabsContent value="amendments"><SimpleTable title="Amendments" rows={related.amendments || []} columns={[['amendmentNumber', 'Amendment'], ['amendmentType', 'Type', labelValue], ['existingValue', 'Old Value'], ['proposedValue', 'New Value'], ['additionalCommission', 'Commission', money], ['status', 'Status', labelValue]]} /></TabsContent>
      <TabsContent value="settlement"><SimpleTable title="Vendor Settlement" rows={related.vendorSettlements || []} columns={[['invoiceNumber', 'Invoice'], ['invoiceAmount', 'Invoice Amount', money], ['acceptedAmount', 'Accepted', money], ['paidAmount', 'Paid', money], ['balancePayable', 'Balance', money], ['status', 'Status', labelValue]]} /></TabsContent>
      <TabsContent value="recovery"><SimpleTable title="Client Recovery" rows={related.recoveries || []} columns={[['clientName', 'Client'], ['recoverableAmount', 'Recoverable', money], ['billedAmount', 'Billed', money], ['receivedAmount', 'Received', money], ['balanceRecoverable', 'Balance', money], ['ageingDays', 'Ageing Days'], ['status', 'Status', labelValue]]} /></TabsContent>
      <TabsContent value="documents"><div className="space-y-4"><SimpleTable title="Shipments" rows={related.shipments || []} columns={[['shipmentNumber', 'Shipment'], ['shipmentDate', 'Date'], ['shipmentValue', 'Value', money], ['mrrNumber', 'MRR'], ['inspectionStatus', 'Inspection', labelValue], ['status', 'Status', labelValue]]} /><SimpleTable title="Documents" rows={related.documents || []} columns={[['documentType', 'Document', labelValue], ['referenceNumber', 'Reference'], ['documentDate', 'Date'], ['version', 'Version'], ['verificationStatus', 'Verification', labelValue], ['fileUrl', 'File', linkValue]]} /><SimpleTable title="Discrepancies" rows={related.discrepancies || []} columns={[['discrepancyType', 'Type', labelValue], ['description', 'Description'], ['amount', 'Amount', money], ['raisedDate', 'Raised'], ['resolution', 'Resolution'], ['status', 'Status', labelValue]]} /></div></TabsContent>
      <TabsContent value="approvals"><SimpleTable title="Approval History" rows={approvals} columns={[['stage', 'Stage', labelValue], ['requiredRole', 'Required Role'], ['requestedByName', 'Requested By'], ['requestedAt', 'Requested', dateValue], ['decidedByName', 'Decided By'], ['decidedAt', 'Decided', dateValue], ['status', 'Status', labelValue], ['comments', 'Comments']]} /></TabsContent>
      <TabsContent value="audit"><SimpleTable title="Audit Trail" rows={audit} columns={[['createdAt', 'Date', dateValue], ['action', 'Action', labelValue], ['summary', 'Summary'], ['userName', 'User'], ['userRole', 'Role'], ['reason', 'Reason']]} /></TabsContent>
    </Tabs>
  </div>;
}

type Column = [string, string, ((value: any, row: Row) => React.ReactNode)?];
const money = (value: any, row: Row) => formatLcCurrency(Number(value || 0), String(row.currency || 'INR'));
const dateValue = (value: any) => toLcDateInput(value) || '-'; const labelValue = (value: any) => lcLabel(String(value || '')); const linkValue = (value: any) => value ? <a href={String(value)} target="_blank" rel="noreferrer" className="text-cyan-700 hover:underline">Open</a> : '-';
function Metric({ label, value, alert = false }: { label: string; value: string; alert?: boolean }) { return <Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className={`mt-1 text-xl font-bold ${alert ? 'text-rose-700' : ''}`}>{value}</p></CardContent></Card>; }
function InfoCard({ title, items }: { title: string; items: Array<[string, any]> }) { return <Card><CardHeader><CardTitle className="text-lg">{title}</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{items.map(([label, value]) => <div key={label}><p className="text-[11px] uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium">{value || '-'}</p></div>)}</CardContent></Card>; }
function SimpleTable({ title, rows, columns }: { title: string; rows: Row[]; columns: Column[] }) { return <Card className="overflow-hidden"><CardHeader><CardTitle className="text-lg">{title}</CardTitle><CardDescription>{rows.length} record(s)</CardDescription></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow>{columns.map(([, label]) => <TableHead key={label}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((row) => <TableRow key={row.id}>{columns.map(([key, label, formatter]) => <TableCell key={label}>{formatter ? formatter(row[key], row) : String(row[key] ?? '-')}</TableCell>)}</TableRow>)}{!rows.length && <TableRow><TableCell colSpan={columns.length} className="h-24 text-center text-muted-foreground">No {title.toLowerCase()} recorded.</TableCell></TableRow>}</TableBody></Table></div></CardContent></Card>; }
