'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { collection, doc, getDocs, query, updateDoc, where } from 'firebase/firestore';
import GenericCrudPage, { type CrudColumnConfig, type CrudFieldConfig } from '@/components/vehicle-management/generic-crud-page';
import { db } from '@/lib/firebase';
import { useAuth } from '@/components/auth/AuthProvider';
import { useAuthorization } from '@/hooks/useAuthorization';
import { useToast } from '@/hooks/use-toast';
import { applyLCAmendment, type LCActor } from '@/lib/letter-of-credit-service';
import { LC_AMENDMENT_TYPES, LC_COLLECTIONS, LC_DOCUMENT_TYPES, LC_PERMISSION_MODULE, formatLcCurrency, lcLabel, type LCHundi, type LetterOfCredit } from '@/lib/letter-of-credit';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

type WorkspaceKind = 'documents' | 'amendments' | 'vendor-settlement' | 'client-recovery';
type SingleKind = 'shipments' | 'document-records' | 'discrepancies' | Exclude<WorkspaceKind, 'documents'>;
type Config = { title: string; description: string; itemName: string; collectionName: string; resource: string; fields: CrudFieldConfig[]; columns: CrudColumnConfig[] };
const option = (values: readonly string[]) => values.map((value) => ({ value, label: lcLabel(value) }));
const money = (value: any, row: Record<string, any>) => formatLcCurrency(Number(value || 0), String(row.currency || 'INR'));

export default function LCEntityWorkspace({ kind }: { kind: WorkspaceKind }) {
  if (kind !== 'documents') return <SingleWorkspace kind={kind} />;
  return <div className="space-y-4"><div><h1 className="text-2xl font-bold tracking-tight">Shipment & Document Tracking</h1><p className="text-sm text-muted-foreground">Track dispatch, material receipt, versioned documents, verification, and discrepancy resolution.</p></div><Tabs defaultValue="shipments"><TabsList className="grid w-full max-w-xl grid-cols-3"><TabsTrigger value="shipments">Shipments</TabsTrigger><TabsTrigger value="documents">Documents</TabsTrigger><TabsTrigger value="discrepancies">Discrepancies</TabsTrigger></TabsList><TabsContent value="shipments"><SingleWorkspace kind="shipments" /></TabsContent><TabsContent value="documents"><SingleWorkspace kind="document-records" /></TabsContent><TabsContent value="discrepancies"><SingleWorkspace kind="discrepancies" /></TabsContent></Tabs></div>;
}

function SingleWorkspace({ kind }: { kind: SingleKind }) {
  const { user } = useAuth(); const { can } = useAuthorization(); const { toast } = useToast(); const organizationId = user?.organizationId || 'default';
  const [credits, setCredits] = useState<LetterOfCredit[]>([]); const [hundis, setHundis] = useState<LCHundi[]>([]);
  const loadMasters = useCallback(async () => { try { const [lcSnapshot, hundiSnapshot] = await Promise.all([getDocs(query(collection(db, LC_COLLECTIONS.credits), where('organizationId', '==', organizationId))), getDocs(query(collection(db, LC_COLLECTIONS.hundis), where('organizationId', '==', organizationId)))]); setCredits(lcSnapshot.docs.map((item) => ({ id: item.id, ...item.data() } as LetterOfCredit))); setHundis(hundiSnapshot.docs.map((item) => ({ id: item.id, ...item.data() } as LCHundi))); } catch { toast({ title: 'LC master options could not be loaded', variant: 'destructive' }); } }, [organizationId, toast]);
  useEffect(() => { void loadMasters(); }, [loadMasters]);
  const lcField: CrudFieldConfig = { key: 'lcId', label: 'Letter of Credit', type: 'select', required: true, searchable: true, options: credits.map((item) => ({ value: item.id, label: `${item.bankLcNumber} · ${item.vendorName}` })) };
  const configs = useMemo<Record<SingleKind, Config>>(() => ({
    shipments: { title: 'Shipment Tracking', description: 'Dispatch, delivery, inspection, quantity, and MRR status.', itemName: 'LC Shipment', collectionName: LC_COLLECTIONS.shipments, resource: 'Shipment & Documents', fields: [lcField, { key: 'shipmentNumber', label: 'Shipment Number', type: 'text', required: true }, { key: 'shipmentDate', label: 'Shipment Date', type: 'date', required: true }, { key: 'dispatchDocumentNumber', label: 'Dispatch Document', type: 'text' }, { key: 'transportDocumentNumber', label: 'LR / BL Number', type: 'text' }, { key: 'transporter', label: 'Transporter', type: 'text' }, { key: 'quantityShipped', label: 'Quantity Shipped', type: 'number' }, { key: 'shipmentValue', label: 'Shipment Value', type: 'number', required: true }, { key: 'expectedDeliveryDate', label: 'Expected Delivery', type: 'date' }, { key: 'actualDeliveryDate', label: 'Actual Delivery', type: 'date' }, { key: 'goodsReceiptDate', label: 'Goods Receipt Date', type: 'date' }, { key: 'mrrNumber', label: 'MRR Number', type: 'text' }, { key: 'mrrDate', label: 'MRR Date', type: 'date' }, { key: 'inspectionStatus', label: 'Inspection Status', type: 'select', options: option(['PENDING', 'ACCEPTED', 'PARTIALLY_ACCEPTED', 'REJECTED']) }, { key: 'shortageQuantity', label: 'Shortage Quantity', type: 'number' }, { key: 'rejectedQuantity', label: 'Rejected Quantity', type: 'number' }, { key: 'acceptedQuantity', label: 'Accepted Quantity', type: 'number' }, { key: 'status', label: 'Shipment Status', type: 'select', options: option(['AWAITING_SHIPMENT', 'PARTIALLY_SHIPPED', 'FULLY_SHIPPED', 'IN_TRANSIT', 'DELIVERED', 'INSPECTION_PENDING', 'ACCEPTED', 'PARTIALLY_ACCEPTED', 'REJECTED']) }, { key: 'remarks', label: 'Remarks', type: 'textarea' }], columns: [{ key: 'lcNumber', label: 'LC Number' }, { key: 'shipmentNumber', label: 'Shipment' }, { key: 'shipmentDate', label: 'Shipment Date' }, { key: 'shipmentValue', label: 'Value', formatter: money }, { key: 'mrrNumber', label: 'MRR' }, { key: 'inspectionStatus', label: 'Inspection' }, { key: 'status', label: 'Status' }] },
    'document-records': { title: 'LC Documents', description: 'Versioned document upload, reference, verification, and archive state.', itemName: 'LC Document', collectionName: LC_COLLECTIONS.documents, resource: 'Shipment & Documents', fields: [lcField, { key: 'documentType', label: 'Document Type', type: 'select', required: true, searchable: true, options: option(LC_DOCUMENT_TYPES) }, { key: 'referenceNumber', label: 'Reference Number', type: 'text' }, { key: 'documentDate', label: 'Document Date', type: 'date' }, { key: 'fileUrl', label: 'Upload File', type: 'file', required: true, accept: '.pdf,.xlsx,.xls,.doc,.docx,.jpg,.jpeg,.png', maxFileSizeMb: 15 }, { key: 'version', label: 'Version', type: 'number', defaultValue: '1', min: 1 }, { key: 'verificationStatus', label: 'Verification Status', type: 'select', options: option(['PENDING', 'VERIFIED', 'REJECTED']) }, { key: 'status', label: 'Document Status', type: 'select', options: option(['ACTIVE', 'ARCHIVED']) }, { key: 'remarks', label: 'Remarks', type: 'textarea' }], columns: [{ key: 'lcNumber', label: 'LC Number' }, { key: 'documentType', label: 'Document' }, { key: 'referenceNumber', label: 'Reference' }, { key: 'documentDate', label: 'Date' }, { key: 'version', label: 'Version' }, { key: 'verificationStatus', label: 'Verification' }, { key: 'status', label: 'Status' }] },
    discrepancies: { title: 'LC Discrepancies', description: 'Raise, waive, resolve, or reject document and Hundi discrepancies.', itemName: 'LC Discrepancy', collectionName: LC_COLLECTIONS.discrepancies, resource: 'Shipment & Documents', fields: [lcField, { key: 'hundiId', label: 'Hundi / Bill', type: 'select', searchable: true, options: hundis.map((item) => ({ value: item.id, label: `${item.hundiNumber} · ${item.lcNumber}` })) }, { key: 'discrepancyType', label: 'Discrepancy Type', type: 'select', required: true, searchable: true, options: option(['LATE_SHIPMENT', 'LATE_PRESENTATION', 'INVOICE_MISMATCH', 'QUANTITY_MISMATCH', 'VALUE_EXCEEDS_LC', 'MISSING_DOCUMENT', 'INVALID_INSURANCE', 'INCORRECT_CONSIGNEE', 'INCORRECT_TRANSPORT_DOCUMENT', 'EXPIRED_LC', 'DUPLICATE_INVOICE', 'MATERIAL_REJECTED', 'PO_MISMATCH', 'OTHER']) }, { key: 'description', label: 'Description', type: 'textarea', required: true }, { key: 'amount', label: 'Affected Amount', type: 'number' }, { key: 'raisedDate', label: 'Raised Date', type: 'date', required: true }, { key: 'vendorResponse', label: 'Vendor Response', type: 'textarea' }, { key: 'bankResponse', label: 'Bank Response', type: 'textarea' }, { key: 'waiverRequired', label: 'Waiver Required', type: 'select', options: option(['YES', 'NO']) }, { key: 'waiverApprovedBy', label: 'Waiver Approved By', type: 'text' }, { key: 'resolution', label: 'Resolution', type: 'textarea' }, { key: 'resolutionDate', label: 'Resolution Date', type: 'date' }, { key: 'status', label: 'Status', type: 'select', options: option(['OPEN', 'VENDOR_CLARIFICATION_AWAITED', 'BANK_CLARIFICATION_AWAITED', 'WAIVER_PENDING', 'WAIVED', 'REJECTED', 'RESOLVED']) }], columns: [{ key: 'lcNumber', label: 'LC Number' }, { key: 'hundiNumber', label: 'Hundi' }, { key: 'discrepancyType', label: 'Type' }, { key: 'amount', label: 'Amount', formatter: money }, { key: 'raisedDate', label: 'Raised' }, { key: 'status', label: 'Status' }] },
    amendments: { title: 'LC Amendments', description: 'Independent amendment transactions with financial, limit, margin, and bank-confirmation impact.', itemName: 'LC Amendment', collectionName: LC_COLLECTIONS.amendments, resource: 'LC Amendments', fields: [lcField, { key: 'amendmentNumber', label: 'Amendment Number', type: 'text', required: true }, { key: 'requestDate', label: 'Request Date', type: 'date', required: true }, { key: 'amendmentType', label: 'Amendment Type', type: 'select', searchable: true, required: true, options: LC_AMENDMENT_TYPES.map(([value, label]) => ({ value, label })) }, { key: 'existingValue', label: 'Existing Value', type: 'text', required: true }, { key: 'proposedValue', label: 'Proposed Value', type: 'text', required: true }, { key: 'reason', label: 'Reason', type: 'textarea', required: true }, { key: 'financialImpact', label: 'Financial Impact', type: 'number' }, { key: 'limitImpact', label: 'Limit Impact', type: 'number' }, { key: 'additionalMarginAmount', label: 'Additional Margin', type: 'number' }, { key: 'additionalCommission', label: 'Additional Commission', type: 'number' }, { key: 'additionalCharges', label: 'Bank Charges', type: 'number' }, { key: 'effectiveDate', label: 'Effective Date', type: 'date' }, { key: 'bankConfirmationReference', label: 'Bank Confirmation', type: 'text' }, { key: 'status', label: 'Status', type: 'select', options: option(['DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'SUBMITTED_TO_BANK', 'BANK_CONFIRMED', 'REJECTED', 'CANCELLED']) }], columns: [{ key: 'lcNumber', label: 'LC Number' }, { key: 'amendmentNumber', label: 'Amendment' }, { key: 'amendmentType', label: 'Type' }, { key: 'existingValue', label: 'Old Value' }, { key: 'proposedValue', label: 'New Value' }, { key: 'additionalCommission', label: 'Commission', formatter: money }, { key: 'status', label: 'Status' }] },
    'vendor-settlement': { title: 'Vendor Settlement', description: 'Invoice, claimed, accepted, paid, disputed, debit/credit note, and balance-payable control.', itemName: 'Vendor Settlement', collectionName: LC_COLLECTIONS.vendorSettlements, resource: 'Vendor Settlement', fields: [lcField, { key: 'purchaseOrderNumber', label: 'Purchase Order', type: 'text' }, { key: 'invoiceNumber', label: 'Invoice Number', type: 'text', required: true }, { key: 'invoiceAmount', label: 'Invoice Amount', type: 'number', required: true }, { key: 'claimedAmount', label: 'Claimed Amount', type: 'number' }, { key: 'acceptedAmount', label: 'Accepted Amount', type: 'number' }, { key: 'paidAmount', label: 'Paid Amount', type: 'number' }, { key: 'disputedAmount', label: 'Disputed Amount', type: 'number' }, { key: 'debitNote', label: 'Debit Note', type: 'number' }, { key: 'creditNote', label: 'Credit Note', type: 'number' }, { key: 'balancePayable', label: 'Balance Payable', type: 'number' }, { key: 'status', label: 'Settlement Status', type: 'select', options: option(['PENDING_INVOICE', 'HUNDI_AWAITED', 'UNDER_VERIFICATION', 'PARTIALLY_ACCEPTED', 'ACCEPTED', 'PARTIALLY_PAID', 'FULLY_PAID', 'DISPUTED', 'CLOSED']) }, { key: 'remarks', label: 'Remarks', type: 'textarea' }], columns: [{ key: 'lcNumber', label: 'LC Number' }, { key: 'vendorName', label: 'Vendor' }, { key: 'invoiceNumber', label: 'Invoice' }, { key: 'acceptedAmount', label: 'Accepted', formatter: money }, { key: 'paidAmount', label: 'Paid', formatter: money }, { key: 'balancePayable', label: 'Balance', formatter: money }, { key: 'status', label: 'Status' }] },
    'client-recovery': { title: 'Client Recovery Management', description: 'Project-wise recoverable, billed, certified, received, balance, and ageing control.', itemName: 'Client Recovery', collectionName: LC_COLLECTIONS.recoveries, resource: 'Client Recovery', fields: [lcField, { key: 'clientName', label: 'Client', type: 'text', required: true }, { key: 'material', label: 'Material', type: 'text' }, { key: 'recoverableAmount', label: 'Recoverable Amount', type: 'number', required: true }, { key: 'billingReference', label: 'Billing Reference', type: 'text' }, { key: 'billingDate', label: 'Billing Date', type: 'date' }, { key: 'billedAmount', label: 'Amount Billed', type: 'number' }, { key: 'certifiedAmount', label: 'Amount Certified', type: 'number' }, { key: 'receivedAmount', label: 'Amount Received', type: 'number' }, { key: 'receiptDate', label: 'Receipt Date', type: 'date' }, { key: 'expectedRecoveryDate', label: 'Expected Recovery Date', type: 'date' }, { key: 'balanceRecoverable', label: 'Balance Recoverable', type: 'number' }, { key: 'ageingDays', label: 'Ageing Days', type: 'number' }, { key: 'status', label: 'Recovery Status', type: 'select', options: option(['NOT_BILLED', 'BILLING_PENDING', 'BILLED', 'PARTIALLY_RECOVERED', 'FULLY_RECOVERED', 'OVERDUE', 'DISPUTED', 'WRITTEN_OFF']) }, { key: 'remarks', label: 'Remarks', type: 'textarea' }], columns: [{ key: 'lcNumber', label: 'LC Number' }, { key: 'projectName', label: 'Project' }, { key: 'clientName', label: 'Client' }, { key: 'recoverableAmount', label: 'Recoverable', formatter: money }, { key: 'receivedAmount', label: 'Received', formatter: money }, { key: 'balanceRecoverable', label: 'Balance', formatter: money }, { key: 'ageingDays', label: 'Ageing' }, { key: 'status', label: 'Status' }] },
  }), [credits, hundis, lcField]);
  const config = configs[kind];
  const canView = can('View', `${LC_PERMISSION_MODULE}.${config.resource}`); const canAdd = can('Add', `${LC_PERMISSION_MODULE}.${config.resource}`); const canEdit = can('Edit', `${LC_PERMISSION_MODULE}.${config.resource}`); const canExport = can('Export', `${LC_PERMISSION_MODULE}.${config.resource}`) || canView;
  const actor: LCActor | null = user ? { userId: user.id, userName: user.name, role: user.role, organizationId, organizationName: user.organizationName } : null;
  return <GenericCrudPage title={config.title} description={config.description} itemName={config.itemName} collectionName={config.collectionName} fields={config.fields} columns={config.columns} canView={canView} canAdd={canAdd} canEdit={canEdit} canDelete={false} canImport={false} canExport={canExport} exportFileName={kind} uploadPathPrefix={`organizations/${organizationId}/letters-of-credit`} onAfterFetch={(rows) => rows.filter((row) => user?.role === 'Super Admin' || row.organizationId === organizationId)} onBeforeSave={(payload) => {
    const lc = credits.find((item) => item.id === payload.lcId); const hundi = hundis.find((item) => item.id === payload.hundiId); const next: Record<string, any> = { ...payload, organizationId, organizationName: user?.organizationName || '', lcNumber: lc?.bankLcNumber || payload.lcNumber || '', vendorName: lc?.vendorName || payload.vendorName || '', projectId: lc?.projectId || payload.projectId || '', projectName: lc?.projectName || payload.projectName || '', currency: lc?.currency || payload.currency || 'INR', hundiNumber: hundi?.hundiNumber || payload.hundiNumber || '', createdBy: payload.createdBy || user?.id || '', createdByName: payload.createdByName || user?.name || '', updatedBy: user?.id || '', updatedByName: user?.name || '' };
    if (kind === 'vendor-settlement') next.balancePayable = Math.max(0, Number(next.acceptedAmount || next.claimedAmount || 0) - Number(next.paidAmount || 0) - Number(next.debitNote || 0) + Number(next.creditNote || 0));
    if (kind === 'client-recovery') { next.balanceRecoverable = Math.max(0, Number(next.recoverableAmount || 0) - Number(next.receivedAmount || 0)); const expected = next.expectedRecoveryDate ? new Date(`${next.expectedRecoveryDate}T00:00:00`) : null; next.ageingDays = expected ? Math.max(0, Math.floor((Date.now() - expected.getTime()) / 86_400_000)) : 0; if (next.balanceRecoverable <= 0) next.status = 'FULLY_RECOVERED'; else if (Number(next.receivedAmount || 0) > 0) next.status = 'PARTIALLY_RECOVERED'; }
    if (kind === 'discrepancies' && next.status === 'RESOLVED' && !String(next.resolution || '').trim()) throw new Error('Resolution details are required before resolving a discrepancy.');
    if (kind === 'amendments' && String(next.existingValue) === String(next.proposedValue)) throw new Error('Existing and proposed values cannot be the same.');
    return next;
  }} onAfterSave={async ({ id, payload }) => {
    if (!payload.lcId) return;
    if (kind === 'amendments' && payload.status === 'BANK_CONFIRMED' && actor) await applyLCAmendment(id, actor);
    if (kind === 'discrepancies') await updateDoc(doc(db, LC_COLLECTIONS.credits, payload.lcId), { status: ['RESOLVED', 'WAIVED', 'REJECTED'].includes(payload.status) ? 'HUNDI_RECEIVED' : 'DISCREPANCY' });
    if (kind === 'client-recovery') { const snapshot = await getDocs(query(collection(db, LC_COLLECTIONS.recoveries), where('lcId', '==', payload.lcId))); const totals = snapshot.docs.reduce((acc, item) => { const row = item.data(); acc.recoverable += Number(row.recoverableAmount || 0); acc.received += Number(row.receivedAmount || 0); return acc; }, { recoverable: 0, received: 0 }); await updateDoc(doc(db, LC_COLLECTIONS.credits, payload.lcId), { recoverableAmount: totals.recoverable, recoveredAmount: totals.received, balanceRecoverable: Math.max(0, totals.recoverable - totals.received) }); }
  }} />;
}
