
'use client';

import { useState, useEffect } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, Plus, View, ArrowUp, ArrowDown, Shuffle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { db } from '@/lib/firebase';
import { doc, getDoc, collection, query, where, getDocs, orderBy } from 'firebase/firestore';
import type { Department, ExpenseRequest, Project } from '@/lib/types';
import { useToast } from '@/hooks/use-toast';
import { Card, CardContent } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuCheckboxItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogFooter,
  DialogClose,
  DialogDescription,
} from '@/components/ui/dialog';
import { ResizablePanelGroup, ResizablePanel, ResizableHandle } from '@/components/ui/resizable';
import { cn } from '@/lib/utils';
import { format } from 'date-fns';


const baseTableHeaders = [
    'Request No',
    'Timestamp',
    'Generated by Department',
    'Project Name',
    'Head of A/c',
    'Sub-Head of A/c',
    'Remarks',
    'Description',
    'Name of the party'
];

export default function DepartmentExpensesPage() {
  const params = useParams();
  const { toast } = useToast();
  const departmentId = params.departmentId as string;

  const [department, setDepartment] = useState<Department | null>(null);
  const [projects, setProjects] = useState<Project[]>([]);
  const [expenses, setExpenses] = useState<ExpenseRequest[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isSequenceDialogOpen, setIsSequenceDialogOpen] = useState(false);

  // State for column order
  const [columnOrder, setColumnOrder] = useState<string[]>(baseTableHeaders);

  const [columnVisibility, setColumnVisibility] = useState<Record<string, boolean>>(() => 
    baseTableHeaders.reduce((acc, header) => ({ ...acc, [header]: true }), {})
  );
  
  useEffect(() => {
    if (!departmentId) return;

    try {
        const savedOrder = window.localStorage.getItem(`expenseColumnOrder_${departmentId}`);
        if (savedOrder) {
            setColumnOrder(JSON.parse(savedOrder));
        } else {
            setColumnOrder(baseTableHeaders);
        }

        const savedVisibility = window.localStorage.getItem(`expenseColumnVisibility_${departmentId}`);
        if (savedVisibility) {
            setColumnVisibility(JSON.parse(savedVisibility));
        } else {
             setColumnVisibility(baseTableHeaders.reduce((acc, header) => ({ ...acc, [header]: true }), {}));
        }
    } catch (e) {
        console.error("Failed to load column settings from localStorage", e);
        setColumnOrder(baseTableHeaders);
        setColumnVisibility(baseTableHeaders.reduce((acc, header) => ({ ...acc, [header]: true }), {}));
    }
  }, [departmentId]);


  useEffect(() => {
    if (!departmentId) return;
    try {
      window.localStorage.setItem(`expenseColumnVisibility_${departmentId}`, JSON.stringify(columnVisibility));
    } catch (error) {
      console.error("Failed to save column visibility to localStorage", error);
    }
  }, [columnVisibility, departmentId]);
  
  useEffect(() => {
    if (!departmentId) return;
    try {
        window.localStorage.setItem(`expenseColumnOrder_${departmentId}`, JSON.stringify(columnOrder));
    } catch (e) {
        console.error("Failed to save column order", e);
    }
  }, [columnOrder, departmentId]);


  useEffect(() => {
    if (!departmentId) return;

    const fetchData = async () => {
      setIsLoading(true);
      try {
        const deptDocRef = doc(db, 'departments', departmentId);
        const projectsSnap = await getDocs(collection(db, 'projects'));
        const expensesQuery = query(collection(db, 'expenseRequests'), where('departmentId', '==', departmentId), orderBy('createdAt', 'desc'));

        const [deptDocSnap, expensesSnap] = await Promise.all([
          getDoc(deptDocRef),
          getDocs(expensesQuery)
        ]);

        if (deptDocSnap.exists()) {
          setDepartment({ id: deptDocSnap.id, ...deptDocSnap.data() } as Department);
        } else {
          toast({ title: 'Error', description: 'Department not found.', variant: 'destructive' });
        }
        
        setProjects(projectsSnap.docs.map(doc => ({ id: doc.id, ...doc.data() } as Project)));
        setExpenses(expensesSnap.docs.map(doc => ({ id: doc.id, ...doc.data() } as ExpenseRequest)));
        
      } catch (error) {
        console.error("Error fetching data:", error);
        toast({ title: 'Error', description: 'Failed to fetch department details.', variant: 'destructive' });
      }
      setIsLoading(false);
    };

    fetchData();
  }, [departmentId, toast]);
  
  const getProjectName = (projectId: string) => {
    return projects.find(p => p.id === projectId)?.projectName || 'Unknown Project';
  }
  
  const visibleHeaders = columnOrder.filter(header => columnVisibility[header]);
  
  const moveColumn = (index: number, direction: 'up' | 'down') => {
      const newOrder = [...columnOrder];
      const newIndex = direction === 'up' ? index - 1 : index + 1;
      
      if (newIndex >= 0 && newIndex < newOrder.length) {
          [newOrder[index], newOrder[newIndex]] = [newOrder[newIndex], newOrder[index]];
          setColumnOrder(newOrder);
      }
  };

  const getCellContent = (header: string, expense: ExpenseRequest) => {
    switch (header) {
      case 'Request No':
        return expense.requestNo;
      case 'Timestamp':
        return expense.createdAt ? format(new Date(expense.createdAt), 'dd MMM yyyy, HH:mm') : 'N/A';
      case 'Generated by Department':
        return expense.generatedByDepartment;
      case 'Project Name':
        return getProjectName(expense.projectId);
      case 'Head of A/c':
        return expense.headOfAccount;
      case 'Sub-Head of A/c':
        return expense.subHeadOfAccount;
      case 'Remarks':
        return expense.remarks;
      case 'Description':
        return expense.description;
      case 'Name of the party':
        return expense.partyName;
      default:
        return '';
    }
  };

  if (isLoading && !department) { // Initial page load
    return (
      <div className="w-full px-4 sm:px-6 lg:px-8">
        <div className="mb-6 flex items-center justify-between">
            <div className="flex items-center gap-2">
                <Skeleton className="h-10 w-10" />
                <Skeleton className="h-8 w-64" />
            </div>
            <Skeleton className="h-10 w-36" />
        </div>
        <Card>
            <CardContent className="p-0">
                 <Skeleton className="h-96 w-full" />
            </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <>
    <div className="w-full px-4 sm:px-6 lg:px-8">
        <div className="mb-6 flex items-center justify-between">
            <div className="flex items-center gap-2">
                <Link href="/expenses">
                <Button variant="ghost" size="icon">
                    <ArrowLeft className="h-6 w-6" />
                </Button>
                </Link>
                <h1 className="text-2xl font-bold">
                {department ? `${department.name} Department Expenses` : 'Department Expenses'}
                </h1>
            </div>
            <div className="flex items-center gap-2">
                <Dialog open={isSequenceDialogOpen} onOpenChange={setIsSequenceDialogOpen}>
                    <DialogTrigger asChild>
                        <Button variant="outline">
                            <Shuffle className="mr-2 h-4 w-4" /> Edit Sequence
                        </Button>
                    </DialogTrigger>
                    <DialogContent>
                        <DialogHeader>
                            <DialogTitle>Edit Column Sequence</DialogTitle>
                            <DialogDescription>Use the arrows to reorder the columns. Your changes will be saved automatically.</DialogDescription>
                        </DialogHeader>
                        <div className="py-4 space-y-2">
                            {columnOrder.map((header, index) => (
                                <div key={header} className="flex items-center justify-between p-2 border rounded-md">
                                    <span className="font-medium">({index + 1}) {header}</span>
                                    <div className="flex items-center">
                                        <Button variant="ghost" size="icon" disabled={index === 0} onClick={() => moveColumn(index, 'up')}>
                                            <ArrowUp className="h-4 w-4" />
                                        </Button>
                                        <Button variant="ghost" size="icon" disabled={index === columnOrder.length - 1} onClick={() => moveColumn(index, 'down')}>
                                            <ArrowDown className="h-4 w-4" />
                                        </Button>
                                    </div>
                                </div>
                            ))}
                        </div>
                         <DialogFooter>
                            <DialogClose asChild>
                                <Button>Done</Button>
                            </DialogClose>
                        </DialogFooter>
                    </DialogContent>
                </Dialog>

                <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                        <Button variant="outline">
                            <View className="mr-2 h-4 w-4" />
                            Columns
                        </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end">
                        <DropdownMenuLabel>Toggle columns</DropdownMenuLabel>
                        <DropdownMenuSeparator />
                        {columnOrder.map((header, index) => (
                            <DropdownMenuCheckboxItem
                                key={header}
                                className="capitalize"
                                checked={columnVisibility[header]}
                                onCheckedChange={(value) =>
                                    setColumnVisibility(prev => ({...prev, [header]: !!value}))
                                }
                            >
                                <span className="mr-2 font-mono text-xs w-5 text-center">({index + 1})</span>{header}
                            </DropdownMenuCheckboxItem>
                        ))}
                    </DropdownMenuContent>
                </DropdownMenu>
                <Link href={`/expenses/new-request?departmentId=${departmentId}`}>
                    <Button>
                        <Plus className="mr-2 h-4 w-4"/>
                        New Expense Request
                    </Button>
                </Link>
            </div>
        </div>
      
        <Card>
            <CardContent className="p-0">
                <ResizablePanelGroup direction="horizontal" className="min-w-full rounded-lg border">
                    <ResizablePanel defaultSize={100}>
                         <div className="overflow-x-auto">
                            <Table>
                                <TableHeader>
                                    <TableRow>
                                        {visibleHeaders.map((header) => (
                                          <TableHead key={header} className="whitespace-nowrap px-4">{header}</TableHead>
                                        ))}
                                    </TableRow>
                                </TableHeader>
                                <TableBody>
                                    {isLoading ? (
                                        Array.from({ length: 5 }).map((_, i) => (
                                            <TableRow key={i}>
                                                {visibleHeaders.map(header => (
                                                    <TableCell key={header}><Skeleton className="h-5 w-full" /></TableCell>
                                                ))}
                                            </TableRow>
                                        ))
                                    ) : expenses.length > 0 ? (
                                        expenses.map(expense => (
                                            <TableRow key={expense.id}>
                                                {visibleHeaders.map(header => (
                                                    <TableCell key={header} className="whitespace-nowrap">
                                                        {getCellContent(header, expense)}
                                                    </TableCell>
                                                ))}
                                            </TableRow>
                                        ))
                                    ) : (
                                        <TableRow>
                                            <TableCell colSpan={visibleHeaders.length} className="text-center h-24">
                                                No expense requests found.
                                            </TableCell>
                                        </TableRow>
                                    )}
                                </TableBody>
                            </Table>
                        </div>
                    </ResizablePanel>
                    <ResizableHandle withHandle />
                </ResizablePanelGroup>
            </CardContent>
        </Card>
    </div>
    </>
  );
}

    