

'use client';

import { useState, useEffect, useRef, useMemo } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, Plus, View, ArrowUp, ArrowDown, Shuffle, ShieldAlert, Search, Calendar as CalendarIcon } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { db } from '@/lib/firebase';
import { doc, getDoc, collection, query, where, getDocs, orderBy, setDoc } from 'firebase/firestore';
import type { Department, ExpenseRequest, Project, UserSettings } from '@/lib/types';
import { useToast } from '@/hooks/use-toast';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuCheckboxItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogFooter,
  DialogClose,
  DialogDescription,
} from '@/components/ui/dialog';
import { format, startOfWeek, endOfWeek, startOfMonth, endOfMonth, subMonths, startOfToday, endOfToday } from 'date-fns';
import { DateRange } from 'react-day-picker';
import { useAuth } from '@/components/auth/AuthProvider';
import { useAuthorization } from '@/hooks/useAuthorization';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Calendar } from '@/components/ui/calendar';
import { cn } from '@/lib/utils';


const baseTableHeaders = [
    'Request No',
    'Timestamp',
    'Generated by Department',
    'Project Name',
    'Amount',
    'Head of A/c',
    'Sub-Head of A/c',
    'Remarks',
    'Description',
    'Name of the party',
    'Reception No',
    'Reception Date'
];

export default function DepartmentExpensesPage() {
  const { departmentId } = useParams() as { departmentId: string };
  const { toast } = useToast();
  const { user, loading: isAuthLoading } = useAuth();
  const { can } = useAuthorization();
  const settingsKey = `expenses_${departmentId}`;
  
  const isInitialMount = useRef(true);

  const [department, setDepartment] = useState<Department | null>(null);
  const [projects, setProjects] = useState<Project[]>([]);
  const [expenses, setExpenses] = useState<ExpenseRequest[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isSequenceDialogOpen, setIsSequenceDialogOpen] = useState(false);

  // State for column order
  const [columnOrder, setColumnOrder] = useState<string[]>(baseTableHeaders);
  const [columnVisibility, setColumnVisibility] = useState<Record<string, boolean>>(
    baseTableHeaders.reduce((acc, header) => ({ ...acc, [header]: true }), {})
  );

  const [filters, setFilters] = useState({
      requestNo: '',
      projectName: 'all',
      partyName: '',
      dateRange: {
        from: startOfMonth(new Date()),
        to: endOfMonth(new Date()),
      } as DateRange | undefined,
  });
  
  const canViewPage = can('View', 'Expenses.Departments', departmentId) || can('View All', 'Expenses');
  const canCreate = can('Create', 'Expenses.Departments', departmentId);

  const handleFilterChange = (field: keyof Omit<typeof filters, 'dateRange'>, value: string) => {
    setFilters(prev => ({ ...prev, [field]: value }));
  };
  
  const handleDateRangeChange = (dateRange: DateRange | undefined) => {
    setFilters(prev => ({...prev, dateRange}));
  };

  const filteredExpenses = useMemo(() => {
    return expenses.filter(exp => {
      const project = projects.find(p => p.id === exp.projectId);
      const expDate = new Date(exp.createdAt);
      const isDateMatch = filters.dateRange?.from && filters.dateRange?.to 
                ? expDate >= filters.dateRange.from && expDate <= filters.dateRange.to
                : true;
      return (
        isDateMatch &&
        (filters.requestNo === '' || exp.requestNo.toLowerCase().includes(filters.requestNo.toLowerCase())) &&
        (filters.partyName === '' || exp.partyName.toLowerCase().includes(filters.partyName.toLowerCase())) &&
        (filters.projectName === 'all' || exp.projectId === filters.projectName)
      );
    });
  }, [expenses, filters, projects]);


  useEffect(() => {
    if (!user || isAuthLoading) return;
    const fetchSettings = async () => {
      const settingsRef = doc(db, 'userSettings', user.id);
      const settingsSnap = await getDoc(settingsRef);
      if (settingsSnap.exists()) {
        const settings = settingsSnap.data() as UserSettings;
        const pageSettings = settings.columnPreferences?.[settingsKey];
        if (pageSettings) {
          // Ensure all base headers are present in the loaded settings
          const mergedVisibility = {
            ...baseTableHeaders.reduce((acc, h) => ({ ...acc, [h]: true }), {}),
            ...pageSettings.visibility
          };
          const mergedOrder = [
            ...pageSettings.order,
            ...baseTableHeaders.filter(h => !pageSettings.order.includes(h))
          ];
          setColumnVisibility(mergedVisibility);
          setColumnOrder(mergedOrder);
        }
      }
    };
    fetchSettings();
  }, [user, settingsKey, isAuthLoading]);

  const saveColumnSettings = async (order: string[], visibility: Record<string, boolean>) => {
    if (!user) return;
    try {
        const settingsRef = doc(db, 'userSettings', user.id);
        const settingsSnap = await getDoc(settingsRef);
        const currentSettings = settingsSnap.exists() ? settingsSnap.data() : { columnPreferences: {} };

        const newPreferences = {
            ...currentSettings.columnPreferences,
            [settingsKey]: {
                order: order,
                visibility: visibility,
            }
        };
        await setDoc(settingsRef, { ...currentSettings, columnPreferences: newPreferences }, { merge: true });
    } catch (e) {
        console.error("Failed to save column settings to Firestore", e);
        toast({ title: "Error", description: "Could not save your column preferences.", variant: "destructive" });
    }
  };
  
  useEffect(() => {
      if (isInitialMount.current) {
          isInitialMount.current = false;
      } else {
          if (user) {
              saveColumnSettings(columnOrder, columnVisibility);
          }
      }
  }, [columnOrder, columnVisibility, user]);
  

  useEffect(() => {
    if (!departmentId || isAuthLoading) return;
    
    if(!canViewPage) {
        setIsLoading(false);
        return;
    }

    const fetchData = async () => {
      setIsLoading(true);
      try {
        const deptDocRef = doc(db, 'departments', departmentId);
        const projectsSnap = await getDocs(collection(db, 'projects'));
        
        const expensesQuery = query(collection(db, 'expenseRequests'), where('departmentId', '==', departmentId));

        const [deptDocSnap, expensesSnap] = await Promise.all([
          getDoc(deptDocRef),
          getDocs(expensesQuery)
        ]);

        if (deptDocSnap.exists()) {
          setDepartment({ id: deptDocSnap.id, ...deptDocSnap.data() } as Department);
        } else {
          toast({ title: 'Error', description: 'Department not found.', variant: 'destructive' });
        }
        
        setProjects(projectsSnap.docs.map(doc => ({ id: doc.id, ...doc.data() } as Project)));

        const fetchedExpenses = expensesSnap.docs.map(doc => ({ id: doc.id, ...doc.data() } as ExpenseRequest));
        // Sort in the browser instead of in the query
        fetchedExpenses.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
        setExpenses(fetchedExpenses);
        
      } catch (error: any) {
        console.error("Error fetching data:", error);
        if (error.code === 'failed-precondition') {
             toast({
                title: 'Database Index Required',
                description: "This query requires a custom index. Please check your Firebase console.",
                variant: 'destructive',
                duration: 10000,
             });
        } else {
            toast({ title: 'Error', description: 'Failed to fetch department details.', variant: 'destructive' });
        }
      }
      setIsLoading(false);
    };

    fetchData();
  }, [departmentId, toast, isAuthLoading, canViewPage]);
  
  const getProjectName = (projectId: string) => {
    return projects.find(p => p.id === projectId)?.projectName || 'Unknown Project';
  }
  
  const visibleHeaders = columnOrder.filter(header => columnVisibility[header]);
  
  const moveColumn = (index: number, direction: 'up' | 'down') => {
      const newOrder = [...columnOrder];
      const newIndex = direction === 'up' ? index - 1 : index + 1;
      
      if (newIndex >= 0 && newIndex < newOrder.length) {
          [newOrder[index], newOrder[newIndex]] = [newOrder[newIndex], newOrder[index]];
          setColumnOrder(newOrder);
      }
  };

  const getCellContent = (header: string, expense: ExpenseRequest) => {
    switch (header) {
      case 'Request No':
        return expense.requestNo;
      case 'Timestamp':
        return expense.createdAt ? format(new Date(expense.createdAt), 'dd MMM yyyy, HH:mm') : 'N/A';
      case 'Generated by Department':
        return expense.generatedByDepartment;
      case 'Project Name':
        return getProjectName(expense.projectId);
      case 'Amount':
        return `₹ ${(expense.amount || 0).toLocaleString()}`;
      case 'Head of A/c':
        return expense.headOfAccount;
      case 'Sub-Head of A/c':
        return expense.subHeadOfAccount;
      case 'Remarks':
        return expense.remarks;
      case 'Description':
        return (
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger>
                <p className="truncate max-w-[200px]">{expense.description}</p>
              </TooltipTrigger>
              <TooltipContent>
                <p className="max-w-md">{expense.description}</p>
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>
        );
      case 'Name of the party':
        return expense.partyName;
      case 'Reception No':
        return expense.receptionNo || 'N/A';
      case 'Reception Date':
        return expense.receptionDate || 'N/A';
      default:
        return '';
    }
  };

  if (isLoading || isAuthLoading) {
    return (
      <div className="w-full px-4 sm:px-6 lg:px-8">
        <div className="mb-6 flex items-center justify-between">
            <div className="flex items-center gap-2">
                <Skeleton className="h-10 w-10" />
                <Skeleton className="h-8 w-64" />
            </div>
            <Skeleton className="h-10 w-36" />
        </div>
        <Card>
            <CardContent className="p-0">
                 <Skeleton className="h-96 w-full" />
            </CardContent>
        </Card>
      </div>
    );
  }

  if(!canViewPage) {
    return (
      <div className="w-full px-4 sm:px-6 lg:px-8">
        <div className="mb-6 flex items-center gap-2">
            <Link href="/expenses"><Button variant="ghost" size="icon"><ArrowLeft className="h-6 w-6" /></Button></Link>
            <h1 className="text-2xl font-bold">Department Expenses</h1>
        </div>
        <Card>
            <CardHeader><CardTitle>Access Denied</CardTitle><CardDescription>You do not have permission to view this page.</CardDescription></CardHeader>
            <CardContent className="flex justify-center p-8"><ShieldAlert className="h-16 w-16 text-destructive" /></CardContent>
        </Card>
      </div>
    )
  }

  return (
    <>
    <div className="w-full px-4 sm:px-6 lg:px-8">
        <div className="mb-6 flex items-center justify-between">
            <div className="flex items-center gap-2">
                <Link href="/expenses">
                <Button variant="ghost" size="icon">
                    <ArrowLeft className="h-6 w-6" />
                </Button>
                </Link>
                <h1 className="text-2xl font-bold">
                {department ? `${department.name} Department Expenses` : 'Department Expenses'}
                </h1>
            </div>
            <div className="flex items-center gap-2">
                <Dialog open={isSequenceDialogOpen} onOpenChange={setIsSequenceDialogOpen}>
                    <DialogTrigger asChild>
                        <Button variant="outline">
                            <Shuffle className="mr-2 h-4 w-4" /> Edit Sequence
                        </Button>
                    </DialogTrigger>
                    <DialogContent>
                        <DialogHeader>
                            <DialogTitle>Edit Column Sequence</DialogTitle>
                            <DialogDescription>Use the arrows to reorder the columns. Your changes will be saved automatically.</DialogDescription>
                        </DialogHeader>
                        <div className="py-4 space-y-2">
                            {columnOrder.map((header, index) => (
                                <div key={header} className="flex items-center justify-between p-2 border rounded-md">
                                    <span className="font-medium">({index + 1}) {header}</span>
                                    <div className="flex items-center">
                                        <Button variant="ghost" size="icon" disabled={index === 0} onClick={() => moveColumn(index, 'up')}>
                                            <ArrowUp className="h-4 w-4" />
                                        </Button>
                                        <Button variant="ghost" size="icon" disabled={index === columnOrder.length - 1} onClick={() => moveColumn(index, 'down')}>
                                            <ArrowDown className="h-4 w-4" />
                                        </Button>
                                    </div>
                                </div>
                            ))}
                        </div>
                         <DialogFooter>
                            <DialogClose asChild>
                                <Button>Done</Button>
                            </DialogClose>
                        </DialogFooter>
                    </DialogContent>
                </Dialog>

                <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                        <Button variant="outline">
                            <View className="mr-2 h-4 w-4" />
                            Columns
                        </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end">
                        <DropdownMenuLabel>Toggle columns</DropdownMenuLabel>
                        <DropdownMenuSeparator />
                        {baseTableHeaders.map((header) => (
                            <DropdownMenuCheckboxItem
                                key={header}
                                className="capitalize"
                                checked={columnVisibility[header]}
                                onCheckedChange={(value) =>
                                    setColumnVisibility(prev => ({...prev, [header]: !!value}))
                                }
                            >
                                {header}
                            </DropdownMenuCheckboxItem>
                        ))}
                    </DropdownMenuContent>
                </DropdownMenu>
                {canCreate && (
                    <Link href={`/expenses/new-request?departmentId=${departmentId}`}>
                        <Button>
                            <Plus className="mr-2 h-4 w-4"/>
                            New Expense Request
                        </Button>
                    </Link>
                )}
            </div>
        </div>

        <Card className="mb-6">
            <CardContent className="p-4 flex flex-col items-start gap-4">
                <div className="w-full grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                    <div className="relative">
                        <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                        <Input placeholder="Search Request No..." className="pl-8" value={filters.requestNo} onChange={e => handleFilterChange('requestNo', e.target.value)} />
                    </div>
                    <div className="relative">
                         <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                        <Input placeholder="Search Party Name..." className="pl-8" value={filters.partyName} onChange={e => handleFilterChange('partyName', e.target.value)} />
                    </div>
                     <Select value={filters.projectName} onValueChange={value => handleFilterChange('projectName', value)}>
                        <SelectTrigger><SelectValue placeholder="All Projects" /></SelectTrigger>
                        <SelectContent>
                            <SelectItem value="all">All Projects</SelectItem>
                            {projects.map(p => <SelectItem key={p.id} value={p.id}>{p.projectName}</SelectItem>)}
                        </SelectContent>
                    </Select>
                     <Popover>
                        <PopoverTrigger asChild>
                            <Button id="date" variant={"outline"} className={cn("w-full justify-start text-left font-normal", !filters.dateRange && "text-muted-foreground")}>
                                <CalendarIcon className="mr-2 h-4 w-4" />
                                {filters.dateRange?.from ? (filters.dateRange.to ? <>{format(filters.dateRange.from, "LLL dd, y")} - {format(filters.dateRange.to, "LLL dd, y")}</> : format(filters.dateRange.from, "LLL dd, y")) : <span>Pick a date range</span>}
                            </Button>
                        </PopoverTrigger>
                        <PopoverContent className="w-auto p-0" align="start">
                            <Calendar initialFocus mode="range" defaultMonth={filters.dateRange?.from} selected={filters.dateRange} onSelect={handleDateRangeChange} numberOfMonths={2}/>
                        </PopoverContent>
                    </Popover>
                </div>
                <div className="flex items-center gap-2">
                    <Button variant="ghost" onClick={() => handleDateRangeChange({ from: startOfToday(), to: endOfToday() })}>Today</Button>
                    <Button variant="ghost" onClick={() => handleDateRangeChange({ from: startOfWeek(new Date()), to: endOfWeek(new Date()) })}>This Week</Button>
                    <Button variant="ghost" onClick={() => handleDateRangeChange({ from: startOfMonth(new Date()), to: endOfMonth(new Date()) })}>This Month</Button>
                    <Button variant="ghost" onClick={() => handleDateRangeChange({ from: startOfMonth(subMonths(new Date(), 1)), to: endOfMonth(subMonths(new Date(), 1)) })}>Last Month</Button>
                </div>
            </CardContent>
        </Card>
      
        <Card>
            <CardContent className="p-0">
                 <div className="overflow-x-auto border rounded-lg">
                    <Table>
                        <TableHeader>
                            <TableRow>
                                {visibleHeaders.map((header) => (
                                  <TableHead key={header} className="whitespace-nowrap px-4">{header}</TableHead>
                                ))}
                            </TableRow>
                        </TableHeader>
                        <TableBody>
                            {isLoading ? (
                                Array.from({ length: 5 }).map((_, i) => (
                                    <TableRow key={i}>
                                        {visibleHeaders.map(header => (
                                            <TableCell key={header}><Skeleton className="h-5 w-full" /></TableCell>
                                        ))}
                                    </TableRow>
                                ))
                            ) : filteredExpenses.length > 0 ? (
                                filteredExpenses.map(expense => (
                                    <TableRow key={expense.id}>
                                        {visibleHeaders.map(header => (
                                            <TableCell key={header} className="whitespace-nowrap">
                                                {getCellContent(header, expense)}
                                            </TableCell>
                                        ))}
                                    </TableRow>
                                ))
                            ) : (
                                <TableRow>
                                    <TableCell colSpan={visibleHeaders.length} className="text-center h-24">
                                        No expense requests found.
                                    </TableCell>
                                </TableRow>
                            )}
                        </TableBody>
                    </Table>
                </div>
            </CardContent>
        </Card>
    </div>
    </>
  );
}


