
'use client';

import { useState, useEffect } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { db } from '@/lib/firebase';
import { doc, getDoc } from 'firebase/firestore';
import type { Department } from '@/lib/types';
import { useToast } from '@/hooks/use-toast';
import { Card, CardContent } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';

export default function DepartmentExpensesPage() {
  const params = useParams();
  const { toast } = useToast();
  const departmentId = params.departmentId as string;

  const [department, setDepartment] = useState<Department | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    if (!departmentId) return;

    const fetchDepartment = async () => {
      setIsLoading(true);
      try {
        const docRef = doc(db, 'departments', departmentId);
        const docSnap = await getDoc(docRef);
        if (docSnap.exists()) {
          setDepartment({ id: docSnap.id, ...docSnap.data() } as Department);
        } else {
          toast({ title: 'Error', description: 'Department not found.', variant: 'destructive' });
        }
      } catch (error) {
        console.error("Error fetching department:", error);
        toast({ title: 'Error', description: 'Failed to fetch department details.', variant: 'destructive' });
      }
      setIsLoading(false);
    };

    fetchDepartment();
  }, [departmentId, toast]);

  if (isLoading) {
    return (
      <div className="w-full px-4 sm:px-6 lg:px-8">
        <div className="mb-6 flex items-center justify-between">
            <div className="flex items-center gap-2">
                <Skeleton className="h-10 w-10" />
                <Skeleton className="h-8 w-64" />
            </div>
            <Skeleton className="h-10 w-36" />
        </div>
        <Card>
            <CardContent className="p-0">
                 <Skeleton className="h-96 w-full" />
            </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="w-full px-4 sm:px-6 lg:px-8">
        <div className="mb-6 flex items-center justify-between">
            <div className="flex items-center gap-2">
                <Link href="/expenses">
                <Button variant="ghost" size="icon">
                    <ArrowLeft className="h-6 w-6" />
                </Button>
                </Link>
                <h1 className="text-2xl font-bold">
                {department ? `${department.name} Department Expenses` : 'Department Expenses'}
                </h1>
            </div>
            <Link href="/expenses/new-request">
                <Button>
                    <Plus className="mr-2 h-4 w-4"/>
                    New Expense Request
                </Button>
            </Link>
        </div>
      
        <Card>
            <CardContent className="p-0">
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead>Request No</TableHead>
                            <TableHead>Generated by Department</TableHead>
                            <TableHead>Project Name</TableHead>
                            <TableHead>Head of A/c</TableHead>
                            <TableHead>Sub-Head of A/c</TableHead>
                            <TableHead>Reception No</TableHead>
                            <TableHead>Reception Date</TableHead>
                            <TableHead>Remarks</TableHead>
                            <TableHead>Description</TableHead>
                            <TableHead>Name of the party</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        <TableRow>
                            <TableCell colSpan={10} className="text-center h-24">
                                No expense requests found.
                            </TableCell>
                        </TableRow>
                    </TableBody>
                </Table>
            </CardContent>
        </Card>
    </div>
  );
}
